/* Extend the standalone prototype with the baseline modules in the mobile design code. */
const EVENTS = [
  {id:'export',period:'2026年9月',date:'9月12日',title:'华辰第一个出口订单',chapter:'华辰二十六年',confirmed:true,story:'那个马来西亚客户是在展会上认识的，三万美元，那时候对我是一笔很大的钱。合同签完我没敢告诉国平，怕他以为我在吹牛。\n\n交货那天我自己去码头看着集装箱装上去，就站在那里，心里说不出是什么感觉。',segments:[['展会上遇见客户','9月3日','2分30秒'],['谈判那几轮','9月8日','1分55秒'],['看着货装船','9月12日','1分20秒']]},
  {id:'retired',period:'2026年9月',date:'9月5日',title:'退伍那年回柳市',chapter:'当兵三年',confirmed:true,story:'退伍证拿到手的那天，我在营地外面站了很久。三年，说长不长，但出去的时候感觉已经不一样了。回到柳市，街上还是那些电器店。',segments:[['退伍证到手','9月5日','3分22秒']]},
  {id:'met-wife',period:'2026年8月',date:'8月22日',title:'认识美凤',chapter:'跑业务那几年',confirmed:true,story:'认识美凤是在公司的联谊会上，我本来不想去，被同事拉去了。她说话很直接，不绕弯子，跟我一样。\n\n我们第一句话是什么我记不清了，只记得外面在下雨，她把伞落在会场里。',segments:[['联谊会那天','8月18日','2分44秒'],['第一句话之后','8月22日','1分26秒']]},
  {id:'father-workbench',period:'2026年8月',date:'8月10日',title:'父亲的工作台',chapter:'柳市镇的少年',confirmed:true,story:'我父亲做木匠，工作台就放在堂屋里。刨花味我现在还记得。他的手很粗，但做出来的东西很精细。',segments:[['堂屋里的刨花味','8月10日','2分18秒']]},
  {id:'mortgage',period:'2026年7月',date:'7月28日',title:'SARS 那年抵押房子',chapter:'华辰二十六年',confirmed:true,story:'2003 年工厂停工，银行来催贷款，我把房子拿去抵押了。后来美凤知道了，没骂我，只问一句“够不够”。我说够了。她说那就行。',segments:[['抵押房子那天','7月28日','1分55秒']]},
  {id:'son-back',period:'2026年7月',date:'7月5日',title:'儿子回来接班',chapter:'交出去',confirmed:false,story:'思远回来进公司的第一天，我没有特意安排，就让他跟着国平。我不想让他第一天就知道，他爸是董事长。',segments:[['思远第一天上班','7月3日','2分18秒'],['父子之间的事','7月5日','1分44秒']]}
];
const COMMUNITY = [
  {id:'yuzhen',name:'王玉珍',age:68,city:'成都',tag:'纺织厂女工 · 30年',title:'锭子与岁月',image:'daughter',text:'车间每天早上六点半开机，那声音我现在做梦还能听见。三十年换了四个工种，但没有一天迟到过。',likes:284,live:false,slots:[],comments:[['桂花','「没有一天迟到过」——我妈也老说这句。'],['老周','六点半开机声，太熟了。'],['小张','外婆也是纺织厂的，听完想给她也录一本。']]},
  {id:'jianguo',name:'李建国',age:71,city:'哈尔滨',tag:'知青 · 北大荒七年',title:'黑土地上的青春',image:'train',text:'1969 年春天，火车到齐齐哈尔。站台上风很大，我把棉帽子压低了还是冷。后来那七年，冷早就不算什么了。',likes:412,live:false,slots:[],comments:[['北大荒老杨','同一年到的齐齐哈尔，站台的风我记一辈子。'],['梅子','「冷早就不算什么了」，看哭了。']]},
  {id:'suhua',name:'陈素华',age:63,city:'广州',tag:'改革开放第一批个体户',title:'摆摊那几年',image:'westlake',text:'1983 年我在高第街摆摊，卖广州的布料。后来慢慢开了店面。现在那条街早就变样了。',likes:193,live:false,slots:[],comments:[['阿珍','高第街！我年轻时也去进过货。'],['一路向南','摆摊人的胆子都是练出来的。']]},
  {id:'mingyuan',name:'张明远',age:59,city:'武汉',tag:'长江大桥建设者',title:'桥上的十二年',image:'huangshan',text:'焊桥的时候风最大，我们要用绳子把自己绑在钢梁上。高空作业的人，都不说怕字，但心里清楚。',likes:356,live:false,slots:[],comments:[['桥梁小学徒','师傅，向您致敬。'],['汉江边上','「不说怕字，但心里清楚」——真话。']]}
];
const PROS = [
  {id:'shen',name:'沈晓芸',title:'资深口述史编辑',rating:'4.9',sessions:127,live:true,services:[['专业访谈 · 半天','¥680'],['AI + 人工精写版','¥1200'],['全书整理 · 套餐','¥3800']]},
  {id:'chen',name:'陈志远',title:'纪录片导演',rating:'4.8',sessions:84,live:false,services:[['5 分钟口述短片','¥2800'],['家族纪录片','¥8800'],['照片修复与上色','¥28 / 张']]},
  {id:'lin',name:'林思雨',title:'传记写作人',rating:'4.7',sessions:56,live:true,services:[['专业访谈 · 全天','¥1200'],['声音精装版','¥380'],['人工精写版','¥1200']]}
];
const TIERS=[{qty:1,unit:128,label:'1 册'},{qty:2,unit:119,label:'2 册'},{qty:3,unit:108,label:'3 册'},{qty:5,unit:98,label:'5 册+'}];
const PRINT_FORMATS=[{id:'hard',label:'精装实体册',sub:'A5 精装 · 纸质书',delta:0},{id:'pdf',label:'数字 PDF 版',sub:'浏览器导出为 PDF',delta:-40},{id:'audio',label:'有声朗读版',sub:'朗读版式预览',delta:-20}];
const extraSaved=JSON.parse(localStorage.getItem('memo-prototype-extra-v1')||'{}');
Object.assign(state,{storiesView:'list',storyExpanded:null,storySegment:null,deletedStories:extraSaved.deletedStories||[],deletedSegments:extraSaved.deletedSegments||[],liked:extraSaved.liked||[],comments:extraSaved.comments||{},customBooks:extraSaved.customBooks||[],addedPhotos:extraSaved.addedPhotos||[],chatClues:extraSaved.chatClues||[],selectedCommunity:null,selectedPro:null,selectedService:null,selectedSlot:null,orderBook:'life',orderFormat:'hard',orderTier:2,orderDraft:null,photoFile:null,photoPreview:null,photoMode:'album'});
Object.assign(state,{storyDelete:null,segmentDelete:null,topicIndex:0,topicChanges:0,chosenTopic:null,lastSaved:null});
Object.assign(state,{speaking:false,chosenPerson:null});
for(const b of state.customBooks)if(!books.some(x=>x.id===b.id))books.push(b);
function extraPersist(){localStorage.setItem('memo-prototype-extra-v1',JSON.stringify({deletedStories:state.deletedStories,deletedSegments:state.deletedSegments,liked:state.liked,comments:state.comments,customBooks:state.customBooks,addedPhotos:state.addedPhotos,chatClues:state.chatClues}));}
icons.stories='<circle cx="5" cy="6" r="1"/><circle cx="5" cy="12" r="1"/><circle cx="5" cy="18" r="1"/><path d="M9 6h11M9 12h11M9 18h11"/>';
icons.community='<circle cx="8" cy="8" r="3"/><circle cx="17" cy="8" r="2"/><path d="M2 20c0-4 3-6 6-6 2 0 3 1 4 2M13 20c0-3 2-5 4-5s4 2 4 5"/>';
tabMarkup=function(){const tabs=[['home','讲述'],['stories','经历'],['people','人物'],['community','广场'],['books','制作']];return tabs.map(([id,label])=>{const active=state.route===id||(id==='stories'&&state.route==='timeline');return `<button class="tab ${active?'active':''}" data-route="${id}" aria-label="${label}" ${active?'aria-current="page"':''}><svg viewBox="0 0 24 24" aria-hidden="true">${icons[id==='books'?'books':id]}</svg><span>${label}</span>${id==='people'&&countAllUnread()?'<i class="unread-dot" style="position:absolute;right:8px;top:2px;width:6px;height:6px"></i>':''}${id==='community'&&COMMUNITY.some(x=>x.live)?'<i class="unread-dot" style="position:absolute;right:8px;top:2px;width:6px;height:6px"></i>':''}</button>`}).join('');};
function extendedHome(){return home().replace('</section>',`<div class="section-head"><h2>想不起第一句？</h2></div><button class="timeline-peek" data-extra="topics"><img src="${asset('train')}" alt="从照片开始回忆"><div><small>可跳过的起话头</small><strong>从照片或小事开始</strong><span>最多换两组，不会反复追问</span></div><b>›</b></button><div class="section-head"><h2>更多内容</h2></div><div class="quick-grid"><button data-extra="open-photo">＋ 添加照片或线索</button><button data-route="stories">查看全部经历</button><button data-route="community">看看社区故事</button><button data-route="books">制作一本回忆册</button></div></section>`);}
function eventCard(ev){const expanded=state.storyExpanded===ev.id;const segs=ev.segments.map((s,i)=>({...s,id:`${ev.id}-${i}`})).filter(s=>!state.deletedSegments.includes(s.id));return `<article class="event-card soft-card"><div class="event-main"><button class="expand-toggle ${expanded?'on':''}" data-extra="toggle-story" data-id="${ev.id}" aria-label="${expanded?'收起':'展开'}${esc(ev.title)}"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 9l6 6 6-6"/></svg></button><div><strong>${ev.title}</strong><small>${ev.chapter} · ${segs.length} 段语音${ev.confirmed?' · 已确认':''}</small></div><span>${ev.date}</span></div>${expanded?`<div class="event-body"><small>原话整理 · 可回看录音</small><p>${esc(ev.story).replace(/\n\n/g,'</p><p>')}</p><div class="record-actions"><button class="ghost" data-extra="segments" data-id="${ev.id}">查看 ${segs.length} 段原始录音</button><button class="ghost" data-extra="delete-story" data-id="${ev.id}">移除事件</button></div></div>`:''}</article>`;}
function storiesPage(){if(state.storiesView==='timeline')return storiesTimeline();const visible=EVENTS.filter(e=>!state.deletedStories.includes(e.id));const newAudio=state.added.filter(r=>!state.deleted.includes(r.id));const groups=[...new Set(visible.map(e=>e.period))];return `<section class="screen"><div class="topline"><span class="eyebrow">我的经历</span><button class="tiny-action" data-extra="open-photo">＋ 添加内容</button></div><h1 class="subheading">说过的，都在这里</h1><p class="subtext">${visible.length} 件故事，${visible.reduce((n,e)=>n+e.segments.length,0)+newAudio.length} 段语音。每一段都可以单独管理。</p><div class="view-switch"><button data-extra="stories-list" class="selected">故事列表</button><button data-extra="stories-timeline">照片时间轴</button></div>${newAudio.length?`<div class="section-head"><h2>新留下的语音</h2></div>${newAudio.map(r=>`<div class="audio-row"><button class="play" data-play="${r.id}">▶</button><span><strong>${esc(r.title)}</strong><small>${r.date} · ${r.length}</small></span><button class="delete" data-delete="${r.id}">删除</button></div>`).join('')}`:''}${groups.map(g=>`<div class="section-head"><h2>${g}</h2></div>${visible.filter(e=>e.period===g).map(eventCard).join('')}`).join('')}<div style="height:18px"></div><button class="primary green full" data-action="record">讲一段新的经历</button></section>`;}
function memImg(m){return m.src||asset(m.photo);}
function storiesTimeline(){return `<section class="screen"><div class="topline"><span class="eyebrow">我的经历 · 照片时间轴</span><button class="tiny-action" data-extra="open-photo">＋ 照片</button></div><h1 class="subheading">一张照片，一段往事</h1><p class="subtext">同一批经历，换一种沿时间浏览的方式。</p><div class="view-switch"><button data-extra="stories-list">故事列表</button><button data-extra="stories-timeline" class="selected">照片时间轴</button></div><div class="photo-stream" id="photo-stream">${memories.map((x,i)=>`<button class="polaroid ${i===state.memoryIndex?'active':''}" data-memory="${i}"><img src="${memImg(x)}" alt="${esc(x.title)}"><small>${esc(x.date)}</small><strong>${esc(x.title)}</strong></button>`).join('')}</div><div class="year-rail">${memories.map((x,i)=>`<button data-memory="${i}" class="${i===state.memoryIndex?'active':''}" aria-label="跳到${x.year}年"></button>`).join('')}</div>${memoryDetail()}<div class="section-head"><h2>让照片开口</h2></div><button class="primary green full" data-action="record-memory">说说我记得的那一天</button></section>`;}
function memoryDetail(){const m=memories[state.memoryIndex];return `<div class="timeline-detail soft-card"><small>${esc(m.place)} · ${esc(m.date)}</small><h2>${esc(m.title)}</h2><p>${esc(m.story)}</p>${m.person?`<button class="text-link" data-person="${m.person}">看看故事里的人 ›</button>`:''}</div>`;}
function communityPage(){return `<section class="screen"><div class="topline"><span class="eyebrow">故事社区</span><span style="font-size:11px;color:var(--muted)">分享给愿意听的人</span></div><h1 class="subheading">听听别人的一生</h1><p class="subtext">下方均为演示故事；预约与服务选择只在原型内预览。</p><div class="section-head"><h2>专业访谈师</h2></div><div class="pro-strip">${PROS.map(p=>`<button class="pro-card" data-extra="pro" data-id="${p.id}"><span class="initial-avatar">${p.name[0]}</span>${p.live?'<i class="live-pill">直播中</i>':''}<strong>${p.name}</strong><small>${p.title}</small><span>★ ${p.rating} · ${p.sessions} 次</span></button>`).join('')}</div><div class="section-head"><h2>回忆片段</h2></div>${COMMUNITY.map(n=>`<article class="community-card soft-card"><div class="community-author"><span class="initial-avatar">${n.name[0]}</span><span><strong>${n.name}</strong><small>${n.age} 岁 · ${n.city} · ${n.tag}</small></span>${n.live?'<i class="live-pill">直播中</i>':''}</div><button class="community-photo" data-extra="community" data-id="${n.id}"><img src="${asset(n.image)}" alt="${n.title}的演示配图"><span>${n.title} ›</span></button><p>${n.text}</p><div class="community-actions"><button data-extra="like" data-id="${n.id}">${state.liked.includes(n.id)?'♥':'♡'} ${n.likes+(state.liked.includes(n.id)?1:0)}</button><button data-extra="community" data-id="${n.id}">💬 ${(state.comments[n.id]||[]).length} 条讨论</button><button data-extra="community" data-id="${n.id}">看故事 ›</button></div></article>`).join('')}</section>`;}
function communityDetail(){const n=COMMUNITY.find(x=>x.id===state.selectedCommunity);if(!n)return communityPage();return `<section class="screen subscreen">${headerBack('故事社区')}<div class="detail-photo"><img src="${asset(n.image)}" alt="${n.title}演示配图"><span>演示配图</span></div><div class="community-author" style="margin:18px 0"><span class="initial-avatar">${n.name[0]}</span><span><strong>${n.name}</strong><small>${n.age} 岁 · ${n.city} · ${n.tag}</small></span></div><h1 class="subheading">${n.title}</h1><p class="story-text">${n.text}</p><div class="record-actions"><button class="ghost" data-extra="like" data-id="${n.id}">${state.liked.includes(n.id)?'♥ 已喜欢':'♡ 喜欢'}</button><button class="ghost" data-extra="copy-story" data-id="${n.id}">复制故事摘要</button></div><div class="section-head"><h2>留言</h2></div>${(state.comments[n.id]||[]).map(c=>`<div class="note-card soft-card"><small>我的留言 · 本地演示</small><p>${esc(c)}</p></div>`).join('')||'<div class="empty">还没有留言。可以写下听完的感受。</div>'}<form id="comment-form" class="mini-form"><textarea name="comment" placeholder="写下听完的感受" required maxlength="180"></textarea><button class="primary" type="submit">留下本地留言</button></form><div class="section-head"><h2>可预约的时间</h2></div>${n.slots.map(s=>`<button class="option-row ${state.selectedSlot===s?'selected':''}" data-extra="slot" data-id="${esc(s)}">${s}<span>${state.selectedSlot===s?'✓':'›'}</span></button>`).join('')}<button class="primary green full" data-extra="booking" style="margin-top:14px">预览预约</button></section>`;}
function proDetail(){const p=PROS.find(x=>x.id===state.selectedPro);if(!p)return communityPage();return `<section class="screen subscreen">${headerBack('专业访谈师')}<div class="pro-profile"><span class="initial-avatar large">${p.name[0]}</span><h1>${p.name}</h1><p>${p.title} · ★ ${p.rating} · ${p.sessions} 次访谈</p>${p.live?'<i class="live-pill">直播中</i>':''}</div><div class="section-head"><h2>服务与报价</h2></div>${p.services.map((s,i)=>`<button class="option-row ${state.selectedService===i?'selected':''}" data-extra="service" data-id="${i}"><span><strong>${s[0]}</strong><small>结合录音与照片，服务内容以正式说明为准</small></span><b>${s[1]}</b></button>`).join('')}<button class="primary green full" data-extra="booking-pro" style="margin-top:16px">预览咨询方案</button></section>`;}
function newBooksPage(){const markup=booksPage();const tiles=state.customBooks.map(b=>`<button class="book-tile" data-book="${b.id}"><div class="book-cover" style="background:${b.color}"><span class="cover-mark">回 忆 录</span><h3>${esc(b.title)}</h3><span class="cover-foot">陈建华 · 口述</span></div><strong>${esc(b.title)}</strong><small>${esc(b.kind)}</small></button>`).join('');return markup.replace('</div><div class="book-note',`${tiles}</div><div class="book-note`).replace('</section>',`<div class="section-head"><h2>制作与导出</h2></div><div class="quick-grid"><button data-extra="new-book">＋ 新建一本回忆册</button><button data-extra="order" data-id="${state.bookId}">选择成品规格</button><button data-extra="export" data-id="${state.bookId}">导出电子稿</button><button data-extra="open-photo">添加照片</button></div></section>`);}
function readerWithActions(){return readerPage().replace('</section>',`<div class="reader-extra"><button class="ghost" data-extra="speak-page">设备朗读试听</button><button class="ghost" data-extra="export" data-id="${state.bookId}">导出电子稿</button><button class="primary" data-extra="order" data-id="${state.bookId}">制作成品</button></div></section>`);}
function orderPage(){const b=books.find(x=>x.id===state.orderBook)||books[0];const fmt=PRINT_FORMATS.find(x=>x.id===state.orderFormat);const tier=TIERS[state.orderTier];const total=Math.max(0,tier.unit+fmt.delta)*(fmt.id==='hard'?tier.qty:1);return `<section class="screen subscreen">${headerBack('我的书')}<span class="eyebrow">成品规格预览</span><h1 class="subheading">把《${esc(b.title)}》做成一本书</h1><p class="subtext">先选版本与册数；这里只保存方案，不会支付。</p><div class="section-head"><h2>成品版本</h2></div>${PRINT_FORMATS.map(f=>`<button class="option-row ${f.id===state.orderFormat?'selected':''}" data-extra="format" data-id="${f.id}"><span><strong>${f.label}</strong><small>${f.sub}</small></span><b>${f.delta?`¥${Math.max(0,128+f.delta)} 起`:'¥128 起'}</b></button>`).join('')}${fmt.id==='hard'?`<div class="section-head"><h2>册数</h2></div><div class="tier-row">${TIERS.map((t,i)=>`<button data-extra="tier" data-id="${i}" class="${i===state.orderTier?'selected':''}"><strong>${t.label}</strong><small>¥${t.unit} / 册</small></button>`).join('')}</div>`:''}<div class="price-total soft-card"><span>${fmt.label} · ${fmt.id==='hard'?tier.label:'电子版'}</span><strong>¥${total}</strong></div><button class="primary full" data-extra="save-order">保存制作方案</button></section>`;}
function orderDonePage(){return `<section class="screen subscreen">${headerBack('成品规格')}<div class="success-orb">✓</div><h1 class="subheading" style="text-align:center">制作方案已保存</h1><p class="subtext" style="text-align:center">这是交互原型中的方案预览，没有产生订单或付款。</p><div class="note-card soft-card" style="margin-top:25px"><small>我的选择</small><p>${esc(state.orderDraft?.title||'回忆册')} · ${esc(state.orderDraft?.format||'精装实体册')} · ${esc(state.orderDraft?.qty||'1 册')}</p><span>参考价格 ¥${state.orderDraft?.total||0}</span></div><div class="quick-grid" style="margin-top:20px"><button data-route="books">返回我的书</button><button data-extra="export" data-id="${state.orderBook}">导出电子稿</button><button data-extra="copy-book" data-id="${state.orderBook}">复制书名和摘要</button><button data-route="people">看看读者名单</button></div></section>`;}
function newBookPage(){return `<section class="screen subscreen">${headerBack('我的书')}<span class="eyebrow">新建一本回忆册</span><h1 class="subheading">这本书，想叫什么？</h1><p class="subtext">先给书一个名字。</p><form id="new-book-form" class="full-form"><label>书名<input name="title" required maxlength="12" placeholder="如：我走过的山河"></label><label>书的形式<select name="kind"><option value="人生故事">人生故事</option><option value="工作回忆">工作回忆</option><option value="旅游故事">旅游故事</option><option value="家庭小册">家庭小册</option></select></label><label>先写下一句开篇的话<textarea name="intro" maxlength="240" placeholder="这本书想从哪件事开始？"></textarea></label><button class="primary full" type="submit">建好书，去翻一翻</button></form></section>`;}
function photoPage(){return `<section class="screen subscreen">${headerBack('添加内容')}<span class="eyebrow">照片与线索</span><h1 class="subheading">留下一张照片</h1><p class="subtext">照片会存进经历时间轴；聊天内容只作线索。</p><div class="section-head"><h2>添加方式</h2></div><button class="option-row" data-extra="pick-camera"><span><strong>📷 现在拍一张</strong><small>用设备相机拍下当前画面</small></span>›</button><button class="option-row" data-extra="pick-album"><span><strong>🖼 从相册选择</strong><small>选手机或电脑里的照片</small></span>›</button><button class="option-row" data-extra="chat"><span><strong>💬 导入微信聊天线索</strong><small>粘贴聊天摘录，先存到边注</small></span>›</button><input id="photo-file" type="file" accept="image/*" hidden><div class="section-head"><h2>已经添加</h2></div>${state.addedPhotos.map(p=>`<button class="photo-added" data-extra="show-photo" data-id="${p.id}"><span class="mini-photo">▧</span><span><strong>${esc(p.title)}</strong><small>${esc(p.date)} · ${esc(p.place)}</small></span>›</button>`).join('')||'<div class="empty">还没有添加自己的照片。新生成的演示照片已放在文件夹 assets 中。</div>'}</section>`;}
function photoFormPage(){return `<section class="screen subscreen">${headerBack('添加照片')}<h1 class="subheading">说说这张照片</h1><p class="subtext">写下照片来源和大概时间，不确定可以写“约”。</p><div class="upload-preview"><img src="${state.photoPreview}" alt="新选择的照片预览"></div><form id="photo-form" class="full-form"><label>照片标题<input name="title" required maxlength="35" placeholder="这张照片让我想起……"></label><label>拍摄时间<input name="date" required maxlength="25" placeholder="如：约 2012 年春天"></label><label>地点<input name="place" maxlength="35" placeholder="如：杭州西湖"></label><label>关于它的一句话<textarea name="story" maxlength="260" placeholder="这只是你记得的版本，暂不替你扩写"></textarea></label><button class="primary full" type="submit">保存照片到时间轴</button></form></section>`;}
function chatPage(){return `<section class="screen subscreen">${headerBack('添加内容')}<span class="eyebrow">聊天线索 · 边注层</span><h1 class="subheading">从聊天里留一点线索</h1><p class="subtext">粘贴有权使用的聊天摘录，只作提问线索，不进入正文。</p><form id="chat-form" class="full-form"><label>线索标题<input name="title" required maxlength="40" placeholder="如：思远提起的旧照片"></label><label>聊天摘录<textarea name="text" required maxlength="600" placeholder="粘贴与家人的聊天摘录"></textarea></label><button class="primary full" type="submit">存入线索</button></form>${state.chatClues.map(c=>`<div class="note-card soft-card"><small>边注线索 · 本地保存</small><p>${esc(c.title)}</p><span>${esc(c.text)}</span></div>`).join('')}</section>`;}
const OPTIONAL_TOPICS=[
  {title:'从一张旧照片开始',question:'看到这张照片，你最先想起什么？',photo:'train'},
  {title:'从一位家人开始',question:'你想起那个人的时候，脑海里先出现什么样子？',photo:'wife'},
  {title:'从一次远行开始',question:'那趟路上，有什么细节现在还记得？',photo:'huangshan'},
  {title:'从一件小事开始',question:'那时有没有一件平常的小事，让你现在还会想起？',photo:'westlake'}
];
function topicPage(){const t=OPTIONAL_TOPICS[state.topicIndex];return `<section class="screen subscreen">${headerBack('讲一段故事')}<span class="eyebrow">话题线索</span><h1 class="subheading">挑一个想说的</h1><p class="subtext">这不是问卷。你可以自己开口，也可以看一张照片找第一句话。</p><button class="topic-feature soft-card" data-extra="choose-topic"><img src="${asset(t.photo)}" alt="${t.title}"><div><small>${t.title}</small></div></button><div class="record-actions"><button class="ghost" data-extra="cycle-topic" ${state.topicChanges>=2?'disabled':''}>换一组 ${state.topicChanges}/2</button><button class="ghost" data-extra="go-direct">我自己想讲</button></div><div style="height:19px"></div><button class="primary full" data-extra="choose-topic">就讲这个</button></section>`;}
function readyPage(){const t=state.chosenTopic||OPTIONAL_TOPICS[0];return `<section class="screen subscreen">${headerBack('选起话头')}<span class="eyebrow">准备录制</span><h1 class="subheading">想到哪儿，就从哪儿讲</h1><div class="readiness"><p>• 不用从头讲起</p><p>• 记不准也可以照样说</p><p>• 录完你自己回听，再决定留不留</p></div><button class="primary full" data-extra="ready-record">开始录音</button><button class="tiny-action" data-extra="topics" style="width:100%;margin-top:12px">换一个话题</button></section>`;}
function recordDonePage(){const r=state.lastSaved;return `<section class="screen subscreen"><div class="success-orb">✓</div><h1 class="subheading" style="text-align:center">这段讲述已保存</h1><p class="subtext" style="text-align:center">这些细节只有你记得。</p><div class="note-card soft-card" style="margin-top:25px"><small>刚刚完成 · 已保留原声</small><p>${esc(r?.title||'今天的一段故事')}</p><span>${r?.length||'00:00'} · 可以回听，也可以删除</span></div><div class="record-actions"><button class="primary green" data-extra="done-home">回到首页</button><button class="primary green" data-extra="done-more">再录一段</button></div></section>`;}
function previewWithActions(){return previewPage().replace('</section>',`<button class="tiny-action" data-extra="rerecord" style="width:100%;margin-top:14px">重新录制</button></section>`);}
function segmentSheet(){const ev=EVENTS.find(e=>e.id===state.storySegment);if(!ev)return '';const segs=ev.segments.map((s,i)=>({...s,id:`${ev.id}-${i}`})).filter(s=>!state.deletedSegments.includes(s.id));return `<div class="delete-modal"><div class="dialog segment-dialog"><div class="topline"><h2>${ev.title}</h2><button class="tiny-action" data-extra="close-segments">✕</button></div><p>${segs.length} 段原始录音。演示记录无原音频；自己新录的语音可以回听。</p>${segs.map(s=>`<div class="audio-row"><button class="play" data-extra="demo-audio">▶</button><span><strong>${s[0]}</strong><small>${s[1]} · ${s[2]}</small></span><button class="delete" data-extra="delete-segment" data-id="${s.id}">删除</button></div>`).join('')||'<div class="empty">这个事件的原始录音已全部移除。</div>'}</div></div>`;}
function confirmStorySheet(){const ev=EVENTS.find(e=>e.id===state.storyDelete);return `<div class="delete-modal"><div class="dialog"><h2>移除这件经历？</h2><p>“${ev?.title||'这件经历'}”会从列表里隐藏。照片时间轴仍保存独立的照片记录。</p><div class="record-actions"><button class="ghost" data-extra="cancel-story-delete">再想想</button><button class="ghost danger" data-extra="confirm-story-delete">移除事件</button></div></div></div>`;}
const oldBack=back;
back=function(){if(['stories','community','books','people','home','timeline'].includes(state.route)){if(state.route==='timeline'){state.storiesView='list';route('stories');}else route('home');return;}if(['community-detail','pro-detail'].includes(state.route))return route('community');if(['order','order-done','new-book','photo'].includes(state.route))return route('books');if(state.route==='photoform'||state.route==='chat')return route('photo');if(state.route==='topic')return route('home');if(state.route==='ready')return route('topic');if(state.route==='record-done')return route('home');return oldBack();};
render=function(){const pages={home:extendedHome,stories:storiesPage,people:peoplePage,person:personPage,audioall:audioAllPage,timeline:storiesTimeline,community:communityPage,'community-detail':communityDetail,'pro-detail':proDetail,books:newBooksPage,reader:readerWithActions,order:orderPage,'order-done':orderDonePage,'new-book':newBookPage,photo:photoPage,photoform:photoFormPage,chat:chatPage,topic:topicPage,ready:readyPage,'record-done':recordDonePage,record:recordPage,preview:previewWithActions};const fn=pages[state.route]||extendedHome;viewport.innerHTML=fn()+(state.deleteId?dialog():'')+(state.storySegment?segmentSheet():'')+(state.storyDelete?confirmStorySheet():'');const main=['home','stories','people','community','books','timeline'].includes(state.route);tabbar.innerHTML=main?tabMarkup():'';tabbar.classList.toggle('hidden',!main);if(state.route==='timeline'||(state.route==='stories'&&state.storiesView==='timeline')){const stream=$('#photo-stream');stream?.children[state.memoryIndex]?.scrollIntoView({block:'nearest',inline:'center'});if(stream)bindStream(stream);}if(state.route==='reader')bindBookSwipe();};
bindStream=function(stream){let timer;stream.addEventListener('scroll',()=>{clearTimeout(timer);timer=setTimeout(()=>{const cards=[...stream.children];if(!cards.length)return;const middle=stream.getBoundingClientRect().left+stream.clientWidth/2;const idx=cards.reduce((best,c,i)=>Math.abs(c.getBoundingClientRect().left+c.clientWidth/2-middle)<Math.abs(cards[best].getBoundingClientRect().left+cards[best].clientWidth/2-middle)?i:best,0);if(idx!==state.memoryIndex){state.memoryIndex=idx;$('.timeline-detail').outerHTML=memoryDetail();document.querySelectorAll('.year-rail button,.polaroid').forEach((c,i)=>c.classList.toggle('active',i%memories.length===idx));}},80)},{passive:true});};
function rerenderPreserve(){const top=$('.screen')?.scrollTop||0;render();const screen=$('.screen');if(screen)screen.scrollTop=top;}
async function putPhoto(id,file){try{const db=await openAudioDb();const tx=db.transaction('photos','readwrite');tx.objectStore('photos').put(file,id);await new Promise((res,rej)=>{tx.oncomplete=res;tx.onerror=rej});db.close();return true;}catch{return false;}}
async function getPhoto(id){try{const db=await openAudioDb();const tx=db.transaction('photos','readonly');const req=tx.objectStore('photos').get(id);const file=await new Promise((res,rej)=>{req.onsuccess=()=>res(req.result);req.onerror=rej});db.close();return file;}catch{return null;}}
async function loadPhotos(){for(const meta of state.addedPhotos){if(memories.some(m=>m.id===meta.id))continue;const file=await getPhoto(meta.id);if(file)memories.push({...meta,src:URL.createObjectURL(file),local:true});}memories.sort((a,b)=>Number(a.year)-Number(b.year));render();}
function downloadedBook(id){const b=books.find(x=>x.id===id)||books[0];const body=b.pages.map((p,i)=>`<section><small>第 ${i+1} 页</small><h2>${esc(p.title||b.title)}</h2>${p.photo?`<p>照片：${esc(p.caption||p.title)}</p>`:''}<p>${esc(p.text||p.subtitle||'').replace(/\n/g,'<br>')}</p></section>`).join('');const doc=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>${esc(b.title)}</title><style>body{font-family:Songti SC,serif;max-width:700px;margin:50px auto;color:#272727;line-height:1.9;padding:0 24px}section{page-break-after:always;border-bottom:1px solid #ddd;padding:45px 0}h1,h2{font-weight:600}button{padding:12px 18px}</style><h1>${esc(b.title)}</h1><p>陈建华口述 · 电子稿预览</p><button onclick="window.print()">打印 / 另存为 PDF</button>${body}</html>`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([doc],{type:'text/html;charset=utf-8'}));a.download=`${b.title}-电子稿.html`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),30000);toast('电子稿已下载；打开后可打印为 PDF');}
function copyText(value){if(!navigator.clipboard?.writeText)return toast('当前浏览器无法复制');navigator.clipboard.writeText(value).then(()=>toast('已复制到剪贴板')).catch(()=>toast('当前浏览器无法复制'));}
function xiaoyiCard(q){return `<div class="xiaoyi-card soft-card ${state.speaking?'speaking':''}"><div class="xiaoyi-portrait"><img src="${asset('xiaoyi')}" alt="访谈者小忆头像"><i></i></div><div class="xiaoyi-info"><strong>小忆 <small>· AI 访谈者</small></strong><p>${q?`“${esc(q)}”`:'我只问一件事，然后安静听你说。'}</p><button data-extra="speak-question">${state.speaking?'停止播报':'▶ 听小忆读这个问题'}</button></div></div>`;}
const originalExtendedHome=extendedHome;
extendedHome=function(){return originalExtendedHome().replace('<button class="timeline-peek" data-extra="topics">',`<button class="xiaoyi-teaser" data-extra="topics"><img src="${asset('xiaoyi')}" alt="小忆的头像"><span><strong>小忆在这里</strong><small>想不起第一句，就从一个问题开始</small></span><b>›</b></button><button class="timeline-peek" data-extra="topics">`);};
const originalTopicPage=topicPage;
topicPage=function(){return originalTopicPage().replace('<button class="topic-feature',`${xiaoyiCard(OPTIONAL_TOPICS[state.topicIndex].question)}<button class="topic-feature`);};
const originalReadyPage=readyPage;
readyPage=function(){return originalReadyPage().replace('<div class="readiness">',`${xiaoyiCard((state.chosenTopic||OPTIONAL_TOPICS[0]).question)}<div class="readiness">`);};
function speakText(text){if(!('speechSynthesis'in window))return toast('当前浏览器不支持语音播报');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='zh-CN';u.rate=.84;u.pitch=.92;u.volume=1;const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>v.lang.toLowerCase().startsWith('zh')&&!v.name.toLowerCase().includes('child'))||null;u.onstart=()=>{state.speaking=true;rerenderPreserve()};u.onend=u.onerror=()=>{state.speaking=false;rerenderPreserve()};speechSynthesis.speak(u);}
const originalStartRecording=startRecording;
startRecording=async function(){if('speechSynthesis'in window)speechSynthesis.cancel();state.speaking=false;return originalStartRecording();};
const originalRoute=route;
route=function(id){if('speechSynthesis'in window)speechSynthesis.cancel();state.speaking=false;state.storySegment=null;state.storyDelete=null;return originalRoute(id);};
saveRecording=async function(){if(!state.recordBlob)return;const id=`new-${Date.now()}`;const p=state.recordFor||'self';const now=new Date();const title=state.recordTitle||(p==='self'?'今天讲的一段故事':`和${person(p)?.name}的一段故事`);const rec={id,personId:p,title,length:formatSecs(state.recordSeconds),date:`${now.getMonth()+1}月${now.getDate()}日`,user:true};const okay=await dbPut(id,state.recordBlob);if(!okay)return toast('当前浏览器无法保存音频，请换浏览器后重试');state.added.push(rec);persist();state.recordBlob=null;state.lastSaved=rec;route('record-done');};
const extraLink=new URLSearchParams(location.search);
if(['stories','community','topic','ready','order','photo','new-book'].includes(extraLink.get('screen')))state.route=extraLink.get('screen');
if(extraLink.get('view')==='timeline')state.storiesView='timeline';
if(extraLink.get('narrator'))state.selectedCommunity=extraLink.get('narrator');
render();
loadPhotos();
document.addEventListener('click',e=>{
  const el=e.target.closest('[data-extra]');if(!el)return;
  const action=el.dataset.extra,id=el.dataset.id;
  if(action==='stories-list'){state.storiesView='list';route('stories');return;}
  if(action==='stories-timeline'){state.storiesView='timeline';route('stories');return;}
  if(action==='open-photo'){state.photoReturn=state.route;route('photo');return;}
  if(action==='toggle-story'){state.storyExpanded=state.storyExpanded===id?null:id;rerenderPreserve();return;}
  if(action==='segments'){state.storySegment=id;rerenderPreserve();return;}
  if(action==='close-segments'){state.storySegment=null;rerenderPreserve();return;}
  if(action==='demo-audio'){toast('演示记录没有附带真实原音频');return;}
  if(action==='delete-segment'){state.deletedSegments.push(id);extraPersist();rerenderPreserve();toast('这段原始录音已移除');return;}
  if(action==='delete-story'){state.storyDelete=id;rerenderPreserve();return;}
  if(action==='cancel-story-delete'){state.storyDelete=null;rerenderPreserve();return;}
  if(action==='confirm-story-delete'){state.deletedStories.push(state.storyDelete);state.storyDelete=null;state.storyExpanded=null;extraPersist();rerenderPreserve();toast('这件经历已从列表移除');return;}
  if(action==='topics'){route('topic');return;}
  if(action==='speak-question'){if(state.speaking){speechSynthesis.cancel();state.speaking=false;rerenderPreserve();}else speakText(state.route==='ready'?state.chosenTopic?.question||'':OPTIONAL_TOPICS[state.topicIndex].question);return;}
  if(action==='cycle-topic'){if(state.topicChanges<2){state.topicChanges++;state.topicIndex=(state.topicIndex+1)%OPTIONAL_TOPICS.length;rerenderPreserve();}return;}
  if(action==='choose-topic'){state.chosenTopic=OPTIONAL_TOPICS[state.topicIndex];route('ready');return;}
  if(action==='go-direct'){openRecord();return;}
  if(action==='ready-record'){const t=state.chosenTopic;openRecord(state.chosenPerson||null,t?.question||'');return;}
  if(action==='rerecord'){state.recordBlob=null;state.recordSeconds=0;route('record');return;}
  if(action==='done-home'){state.lastSaved=null;route('home');return;}
  if(action==='done-more'){state.lastSaved=null;openRecord();return;}
  if(action==='community'){state.selectedCommunity=id;state.selectedSlot=null;route('community-detail');return;}
  if(action==='pro'){state.selectedPro=id;state.selectedService=null;route('pro-detail');return;}
  if(action==='like'){const ix=state.liked.indexOf(id);if(ix<0)state.liked.push(id);else state.liked.splice(ix,1);extraPersist();rerenderPreserve();return;}
  if(action==='slot'){state.selectedSlot=id;rerenderPreserve();return;}
  if(action==='service'){state.selectedService=Number(id);rerenderPreserve();return;}
  if(action==='booking'){toast(state.selectedSlot?`已选择 ${state.selectedSlot}，正式预约需服务端支持`:'先选一个预约时间');return;}
  if(action==='booking-pro'){toast(state.selectedService!==null?'咨询方案已选，正式预约需服务端支持':'先选择一项服务');return;}
  if(action==='copy-story'){const n=COMMUNITY.find(x=>x.id===id);if(n)copyText(`${n.title}\n${n.text}`);return;}
  if(action==='copy-book'){const b=books.find(x=>x.id===id);if(b)copyText(`${b.title} · 陈建华口述回忆录`);return;}
  if(action==='new-book'){route('new-book');return;}
  if(action==='order'){state.orderBook=id||state.bookId;route('order');return;}
  if(action==='format'){state.orderFormat=id;rerenderPreserve();return;}
  if(action==='tier'){state.orderTier=Number(id);rerenderPreserve();return;}
  if(action==='save-order'){const b=books.find(x=>x.id===state.orderBook)||books[0];const f=PRINT_FORMATS.find(x=>x.id===state.orderFormat);const t=TIERS[state.orderTier];state.orderDraft={title:b.title,format:f.label,qty:f.id==='hard'?t.label:'电子版',total:Math.max(0,t.unit+f.delta)*(f.id==='hard'?t.qty:1)};route('order-done');return;}
  if(action==='export'){downloadedBook(id||state.bookId);return;}
  if(action==='speak-page'){const b=books.find(x=>x.id===state.bookId)||books[0];const p=b.pages[state.pageIndex];speakText(`${p.title||b.title}。${p.text||p.subtitle||''}`);return;}
  if(action==='pick-camera'||action==='pick-album'){const input=$('#photo-file');if(!input)return;input.setAttribute('capture',action==='pick-camera'?'environment':'');if(action==='pick-album')input.removeAttribute('capture');input.click();return;}
  if(action==='chat'){route('chat');return;}
  if(action==='show-photo'){const idx=memories.findIndex(m=>m.id===id);if(idx<0)return toast('这张照片在当前浏览器不可用');state.memoryIndex=idx;state.storiesView='timeline';route('stories');return;}
});
document.addEventListener('change',e=>{if(e.target.id!=='photo-file')return;const file=e.target.files?.[0];if(!file)return;state.photoFile=file;if(state.photoPreview)URL.revokeObjectURL(state.photoPreview);state.photoPreview=URL.createObjectURL(file);route('photoform');});
document.addEventListener('click',e=>{const btn=e.target.closest('button[data-topic]');if(!btn)return;e.preventDefault();e.stopImmediatePropagation();state.chosenPerson=state.personId;state.chosenTopic={title:`和${person(state.personId)?.name||'家人'}的故事`,question:btn.dataset.topic};route('ready');},true);
document.addEventListener('submit',async e=>{
  const form=e.target;if(!['comment-form','new-book-form','photo-form','chat-form'].includes(form.id))return;e.preventDefault();const data=new FormData(form);
  if(form.id==='comment-form'){const text=String(data.get('comment')||'').trim();if(!text)return;const id=state.selectedCommunity;(state.comments[id]||=[]).push(text);extraPersist();rerenderPreserve();toast('留言已保存在本地演示');return;}
  if(form.id==='new-book-form'){const title=String(data.get('title')||'').trim();const kind=String(data.get('kind')||'人生故事');const intro=String(data.get('intro')||'').trim();if(!title)return;const color=kind.includes('旅游')?'#315a48':kind.includes('工作')?'#244564':'#78533f';const b={id:`custom-${Date.now()}`,title,kind,subtitle:'新建回忆册',color,pages:[{type:'cover',title,subtitle:'陈建华口述 · 新书'},{type:'chapter',label:'开篇 · 我的故事',title:'从这里开始',text:intro||'这本书还没有段落。下一次口述，可以从一件小事讲起。'}]};books.push(b);state.customBooks.push(b);extraPersist();state.bookId=b.id;state.pageIndex=0;toast('新书已放入书架');route('reader');return;}
  if(form.id==='chat-form'){const title=String(data.get('title')||'').trim(),text=String(data.get('text')||'').trim();if(!title||!text)return;state.chatClues.unshift({title,text});extraPersist();rerenderPreserve();toast('聊天摘录已存入边注线索');return;}
  if(form.id==='photo-form'){if(!state.photoFile)return toast('先选择一张照片');const id=`photo-${Date.now()}`;const title=String(data.get('title')||'').trim(),date=String(data.get('date')||'').trim(),place=String(data.get('place')||'').trim()||'地点暂未记录',story=String(data.get('story')||'').trim()||'这张照片的故事，等我想起来再讲。';if(!title||!date)return;const okay=await putPhoto(id,state.photoFile);if(!okay)return toast('当前浏览器无法保存照片，请换浏览器重试');const year=(date.match(/(?:19|20)\d{2}/)||[])[0]||String(new Date().getFullYear());const meta={id,year,date,place,title,story,person:null};state.addedPhotos.push(meta);extraPersist();memories.push({...meta,src:state.photoPreview,local:true});memories.sort((a,b)=>Number(a.year)-Number(b.year));state.memoryIndex=memories.findIndex(m=>m.id===id);state.photoFile=null;state.photoPreview=null;state.storiesView='timeline';toast('照片已加入经历时间轴');route('stories');return;}
});
