/* Product-specific refinement of the source mobile navigation and feature flows. */
const GUIDES=[
 {id:'free',kind:'自由讲述',source:'默认话题',title:'今天想到的那件事',q:'你今天最想先讲哪一件事？',img:'narrator',method:'先让讲述者自行决定开头；小忆只在需要时给一个中性的起话头。'},
 {id:'train',kind:'少年经历',source:'默认话题',title:'第一次离开柳市',q:'那次出门，你最先记得路上的什么？',img:'train',method:'从具体路途和感官细节进入，避免要求概括一生。'},
 {id:'service',kind:'当兵三年',source:'默认话题',title:'退伍那天',q:'拿到退伍证的那一天，你记得自己先做了什么？',img:'train',method:'问可回忆的动作，不替讲述者判断那段经历的意义。'},
 {id:'business',kind:'工作经历',source:'默认话题',title:'第一次出省跑业务',q:'带着样品去湖南的那趟路，哪一幕现在还在你脑海里？',img:'workshop',method:'把宏大叙事缩到一趟路和一个画面。'},
 {id:'wife',kind:'人物故事',source:'默认话题',title:'认识美凤',q:'说到第一次认识美凤，你先想起那天的哪个细节？',img:'wife',method:'不要求精准复述第一句话，也不引导评价关系。'},
 {id:'father',kind:'旧物线索',source:'本人拍照 · 父亲工作台',title:'堂屋里的工作台',q:'看着这张工作台的照片，你最先注意到什么？',img:'father',method:'先问照片可见的细节；是否讲父亲，由本人选择。'},
 {id:'expo',kind:'照片线索',source:'协作端上传 · 展会照片',title:'展会上的一张合影',q:'看着这张合影，你记得那天是怎么开始的吗？',img:'expo',method:'照片只给话题方向，不把协作者的猜测放进问题。'},
 {id:'contract',kind:'文件线索',source:'协作端上传 · 旧订单',title:'第一份出口订单',q:'看到这份旧订单，你记得当时是怎样推进这件事的吗？',img:'workshop',method:'订单的时间和金额先待本人确认；问题只问本人经历。'},
 {id:'family',kind:'照片线索',source:'协作端上传 · 家庭照片',title:'西湖边那一天',q:'看这张照片，你先想起那天走到哪里了？',img:'familytrip',method:'用开放的方位问题，不预设每个人的情绪。'},
 {id:'factory',kind:'本人拍照',source:'本人新拍 · 工厂现场',title:'今天的车间',q:'现在站在这里，你先会向年轻时的自己介绍哪一处？',img:'workshop',method:'连接当下场景与过去，但不替本人形成结论。'},
 {id:'huangshan',kind:'旅行照片',source:'本人拍照 · 黄山',title:'等日出的清晨',q:'看到这张黄山照片，你还记得当时周围是什么样吗？',img:'huangshan',method:'从环境声、风和光线唤起叙述，不逼问“感动”。'},
 {id:'son',kind:'协作话题',source:'思远提供 · 回公司照片',title:'思远回来的第一天',q:'思远进公司第一天，你记得自己怎样安排他的工作？',img:'son',method:'协作线索用于选题；主观感受等本人愿意再讲。'}
];
GUIDES.push(
 {id:'school',kind:'少年经历',source:'默认话题',title:'柳市镇放学路',q:'放学走过那些电器作坊时，你最先会看哪一样东西？',img:'old-tool',method:'从固定路线和可见物件进入童年记忆。'},
 {id:'mother-morning',kind:'家人故事',source:'默认话题',title:'母亲的一顿早饭',q:'想起母亲在家的早晨，你先记得厨房里的什么？',img:'mother',method:'日常细节优先，不预设家人的情绪。'},
 {id:'first-job',kind:'工作经历',source:'默认话题',title:'第一次递出名片',q:'你第一次进别人的厂里递名片，记得当时站在哪里吗？',img:'workshop',method:'先问现场，再由本人讲结果。'},
 {id:'partner-start',kind:'工作伙伴',source:'默认话题',title:'和国平第一次搭档',q:'第一次和国平一起做事，你们各自先做了什么？',img:'partner',method:'用合作动作引出人物关系。'},
 {id:'factory-crisis',kind:'工作经历',source:'默认话题',title:'工厂停工的那几天',q:'停工那天，你到厂里最先看到了什么？',img:'community-factory',method:'不以评价或成败词开头，允许跳过。'},
 {id:'daughter-camera',kind:'家人故事',source:'默认话题',title:'思颖拿着相机',q:'思颖小时候拿相机拍你们，你记得她最爱拍什么？',img:'daughter',method:'从具体互动引出女儿的故事。'},
 {id:'morning-walk',kind:'现在的生活',source:'默认话题',title:'江边的清晨',q:'你现在早上走到江边，最常先看见什么？',img:'westlake',method:'先谈现在，由本人决定是否回看过去。'},
 {id:'first-journey',kind:'旅行经历',source:'默认话题',title:'第一次坐绿皮火车',q:'那趟绿皮火车上，哪一种声音现在还记得？',img:'train',method:'感官线索帮助定位一个画面。'},
 {id:'travel-companion',kind:'旅行经历',source:'默认话题',title:'黄山路上的同伴',q:'等黄山日出时，身边是谁？',img:'huangshan',method:'先问身边的人，再听完整段。'},
 {id:'wife-today',kind:'人物故事',source:'默认话题',title:'现在和美凤的早晨',q:'你们现在一起吃早饭时，通常先说起什么？',img:'wife',method:'问当下习惯，保留讲述者的口气。'},
 {id:'old-plane',kind:'旧物线索',source:'本人拍照 · 父亲木刨',title:'一把旧木刨',q:'拿起这把木刨，你还记得父亲怎样用它吗？',img:'old-tool',method:'从旧物的使用动作进入，不猜测照片的年代。'},
 {id:'old-ticket',kind:'文件线索',source:'本人拍照 · 旧车票',title:'那张绿皮火车票',q:'看到这张车票，你先想起当时是怎样出发的？',img:'train',method:'票上的信息只作线索，具体经过由本人讲。'},
 {id:'collab-family',kind:'照片线索',source:'协作端上传 · 家庭合影',title:'一家人走在湖边',q:'看着这张合影，那天走在你旁边的是谁？',img:'familytrip',method:'不猜谁拍了照片或当时心情。'},
 {id:'collab-client',kind:'人物线索',source:'协作端上传 · 客户照片',title:'黄先生来厂里的那次',q:'看到这张照片，你先记得他到厂里后做了什么？',img:'client',method:'客户身份和日期均待本人确认。'},
 {id:'collab-ledger',kind:'文件线索',source:'协作端上传 · 账本页',title:'翻开那本旧账本',q:'看着这页账本，你先想到当时是哪一件事？',img:'old-tool',method:'数字暂不变成问题中的确定事实。'},
 {id:'collab-voice',kind:'协作话题',source:'协作端上传 · 家人语音',title:'家人提到的一趟路',q:'家人说起那趟路时，你自己先想到哪一幕？',img:'familytrip',method:'他人说法只作选题，讲述以本人为主。'}
);
GUIDES.push(
 {id:'wife-photo',kind:'照片线索',source:'协作端上传 · 美凤合影',title:'美凤带来的照片',q:'看着这张照片，你记得那天从哪里来的？',img:'wife',method:'照片引发；不预设当时的情绪。'},
 {id:'daughter-photo',kind:'照片线索',source:'协作端上传 · 思颖童年照片',title:'思颖小时候',q:'你看到这张照片，先认出她在做什么？',img:'daughter',method:'先问可见动作，不加入评价词。'},
 {id:'blurry',kind:'本人照片',source:'本人拍照 · 模糊老照片',title:'一张已经模糊的照片',q:'就算照片不清楚，你还认得这是在什么地方吗？',img:'old-workbench',method:'模糊照片仍可作为地点线索。'},
 {id:'lake-own',kind:'本人照片',source:'本人拍照 · 湖边旧照',title:'照片前后的那段路',q:'你拍下这张照片前后，记得走了哪一段路？',img:'westlake',method:'用照片前后连接一个完整事件。'},
 {id:'service-item',kind:'旧物线索',source:'本人拍照 · 退伍证',title:'拿到退伍证那天',q:'看到这件旧物，你先想起拿到它的哪一天？',img:'old-tool',method:'从拿到物件的动作和时间进入。'},
 {id:'old-phone',kind:'旧物线索',source:'本人拍照 · 旧电话',title:'办公室第一部电话',q:'那部电话当时放在哪里？',img:'old-tool',method:'先问位置；声音细节留作下一轮。'},
 {id:'father-tool-photo',kind:'旧物线索',source:'协作端上传 · 父亲木工工具',title:'父亲用过的旧工具',q:'这件东西以前放在哪里？',img:'old-tool',method:'协作照片只给物件方向，不说是谁使用过。'},
 {id:'container',kind:'工作经历',source:'默认话题',title:'集装箱装上船',q:'你站在码头时，周围有什么画面现在还记得？',img:'expo',method:'用视觉与听觉帮助重建现场。'},
 {id:'mother-kitchen',kind:'家人故事',source:'默认话题',title:'家里厨房的早晨',q:'说到家里吃饭，你先想起厨房里的什么？',img:'mother',method:'从气味、味道或物件进入。'},
 {id:'liushi',kind:'少年经历',source:'默认话题',title:'柳市镇的早晨',q:'小时候一早出门，街上通常是什么样？',img:'train',method:'青年期与生活场景锚点。'},
 {id:'startup',kind:'工作伙伴',source:'默认话题',title:'决定一起创业',q:'你记得那次决定最初是怎样谈起来的吗？',img:'partner',method:'只追问讲述者自己的事件经过。'},
 {id:'handover',kind:'人物故事',source:'默认话题',title:'思远跟着国平工作',q:'思远第一次跟着国平工作，你记得那天怎样安排的？',img:'son',method:'人物锚点与具体安排动作。'},
 {id:'factory-now',kind:'当下场景',source:'本人拍照 · 现在的厂房',title:'再走进这间厂房',q:'现在再走进这间厂房，哪一处最先让你想到过去？',img:'workshop',method:'利用当下环境与过去环境的重叠。'},
 {id:'son-document',kind:'文件线索',source:'协作端上传 · 思远的旧文件',title:'文件里的那件事',q:'看到这份文件，你记得这件事当时怎样开始的吗？',img:'son',method:'不复述文件内容为事实。'},
 {id:'assistant-order',kind:'文件线索',source:'协作端上传 · 助理整理的旧订单',title:'是谁先接起那一单',q:'看到这份订单，你记得那一单是谁先接起来的吗？',img:'assistant',method:'行为问题保持中性，不评价结果。'},
 {id:'family-message',kind:'聊天线索',source:'协作端上传 · 家人聊天摘录',title:'家人提到的一件事',q:'家人提到这件事时，你自己先想到哪个画面？',img:'familytrip',method:'强调讲述者自己的来源，协作内容另存。'}
);
Object.assign(state,{guideIndex:0,guideChanges:0,uploadSheet:false,aiContext:'home',aiMessages:[],timelinePaused:false,fullPageIndex:1,editPageIndex:null,orderQty:1,finalFormat:'hard',readIndex:-1});
Object.assign(state,{followFriend:'yuzhen',followNews:'photo',friendMessages:JSON.parse(localStorage.getItem('memo-prototype-friend-chat-v1')||'[]')});
Object.assign(state,{demoRecording:false,demoSeconds:0,agentRaw:false,agentConfirmed:false,agentQuestion:'person',agentSupplement:'',agentSaved:false});
Object.assign(state,{inlineEditing:false,pageAiQuestion:'detail',pageAiReply:'',pageNotes:JSON.parse(localStorage.getItem('memo-prototype-page-notes-v1')||'{}')});
state.addedFiles=JSON.parse(localStorage.getItem('memo-prototype-files-v1')||'[]');
const finalLink=new URLSearchParams(location.search);
if(['home','stories','people','community','books','reader','ai','guides','fullpage','order','photo','chat','file','follow','friend','news','agent-demo-record','agent-review','agent-done'].includes(finalLink.get('screen')))state.route=finalLink.get('screen');
if(finalLink.get('screen')==='reader'&&finalLink.get('spread'))state.pageIndex=1;
if(finalLink.get('screen')==='stories'&&finalLink.get('view')==='timeline')state.storiesView='timeline';
if(finalLink.get('screen')==='agent-demo-record'&&finalLink.get('live')==='1'){state.demoRecording=true;state.demoSeconds=8;}
if(finalLink.get('screen')==='fullpage'&&finalLink.get('edit')==='1')state.inlineEditing=true;
const pageEdits=JSON.parse(localStorage.getItem('memo-prototype-page-edits-v1')||'{}');
const aiSaved=JSON.parse(localStorage.getItem('memo-prototype-ai-chat-v1')||'[]');
state.aiMessages=aiSaved;
for(const m of memories){if(m.year==='1994'){m.year='1996';m.date='1996 年 · 认识美凤';m.story=m.story.replace('1994','1996')}}
memories[0]={year:'1980',date:'约 1980 年 · 柳市镇',place:'家里的堂屋',title:'父亲的木匠工作台',photo:'old-workbench',story:'我父亲做木匠，工作台就放在堂屋里。刨花味我现在还记得，早上起来空气里就是那个味。',person:'father'};
memories.splice(1,0,{year:'1985',date:'1985 年 · 第一次远行',place:'绿皮火车上',title:'从车窗看见的田野',photo:'train',story:'第一次坐火车出远门，车厢里人很多。我靠着窗口，看外面的田野一片一片往后退。',person:'mother'});
books.find(b=>b.id==='life').pages[2].caption='认识美凤 · 1996 年';
books.find(b=>b.id==='work').pages.push(
 {type:'photo',label:'2001 年 · 展会',title:'认识马来西亚客户',photo:'expo',caption:'展会现场 · 旧照片',text:'那个马来西亚客户是在展会上认识的。三万美元，那时候对我是一笔很大的钱。'},
 {type:'chapter',label:'第三章 · 华辰二十六年',title:'把房子拿去抵押',text:'2003 年工厂停工，银行来催贷款，我把房子拿去抵押了。后来美凤知道了，只问一句“够不够”。'}
);
books.find(b=>b.id==='life').pages.push(
 {type:'chapter',label:'第五章 · 交出去',title:'思远回公司那天',text:'思远回来进公司的第一天，我没有特意安排，就让他跟着国平。我不想让他第一天就知道，他爸是董事长。'},
 {type:'photo',label:'家人的路',title:'沿着西湖慢慢走',photo:'familytrip',caption:'一家人的西湖日 · 2012 年',text:'思颖拿着相机，思远走在前头。那天没有安排很满的行程。'}
);
books.find(b=>b.id==='travel').pages.push(
 {type:'photo',label:'旅途里的人',title:'那天一起走的人',photo:'familytrip',caption:'杭州 · 2012 年',text:'大家沿着湖边慢慢走。我记得风吹过来时，柳枝一直在晃。'},
 {type:'chapter',label:'一段路',title:'照片外的声音',text:'山上冷，风也很大。太阳从云海里升起来的时候，周围的人都不说话了。'}
);
COMMUNITY[0].image='community-factory';COMMUNITY[1].image='community-north';COMMUNITY[2].image='community-market';COMMUNITY[3].image='community-bridge';
COMMUNITY.forEach((n,i)=>{n.avatar=['community-yuzhen','community-jianguo','community-suhua','community-mingyuan'][i];n.photos=[n.image,['workshop','train','familytrip','huangshan'][i],['expo','familytrip','westlake','workshop'][i]];});
PROS.forEach((p,i)=>p.avatar=['pro-shen','pro-chen','pro-lin'][i]);
const sourceRender=render,sourceBack=back;
const fyAvatar=(name,alt)=>'<img src="'+asset(name)+'" alt="'+esc(alt)+'" onerror="this.src=\'assets/xiaoyi.png\'">';
function assistantMini(context,question){return `<div class="assistant-mini"><img src="${asset('xiaoyi')}" alt="小忆头像"><div><strong>小忆</strong><span>${esc(question||'我会安静听你讲。')}</span></div><button data-final="ai-open" data-context="${context}">对话 ›</button></div>`;}
function guideImg(g){return g.src||asset(g.img)}
function syncPhotoGuides(){for(const p of state.addedPhotos){const id=`self-photo-${p.id}`;if(GUIDES.some(g=>g.id===id))continue;const m=memories.find(x=>x.id===p.id);GUIDES.push({id,kind:'本人照片',source:`本人拍照 · ${p.title}`,title:p.title,q:`看着这张照片，你最先想起那天的什么？`,img:'old-workbench',src:m?.src||null,method:'照片来源先由本人确认，问题只邀请本人讲记得的画面。',photoId:p.id})}for(const g of GUIDES.filter(x=>x.photoId)){g.src=memories.find(m=>m.id===g.photoId)?.src||g.src}}
function syncEvidenceGuides(){for(const f of state.addedFiles){const id=`file-guide-${f.id}`;if(GUIDES.some(g=>g.id===id))continue;GUIDES.push({id,kind:'文件线索',source:`协作端上传 · ${f.name}`,title:f.title,q:`看到这份${f.title}，你先想起它涉及的哪一段经历？`,img:'expo',method:'文件本身只是待核对线索，问题不复述其内容为事实。'})}for(const c of state.chatClues){const id=`chat-guide-${c.title}`;if(GUIDES.some(g=>g.id===id))continue;GUIDES.push({id,kind:'聊天线索',source:'协作端上传 · 微信线索',title:c.title,q:`家人提起${c.title}，你自己最先想起哪件事？`,img:'familytrip',method:'聊天里的说法不直接进入正文；只给本人一个开放的起话头。'})}}
function finalTabs(){const tabs=[['home','录音','home'],['stories','经历','stories'],['upload','＋','plus'],['community','广场','community'],['books','我的','books']];return tabs.map(([id,label,icon])=>`<button class="tab ${state.route===id?'active':''} ${id==='upload'?'tab-upload':''}" ${id==='upload'?'data-final="upload-sheet"':`data-route="${id}"`} aria-label="${id==='upload'?'上传内容':label}"><svg viewBox="0 0 24 24" aria-hidden="true">${id==='upload'?'<path d="M12 4v16M4 12h16"/>':icons[icon]}</svg><span>${id==='upload'?'上传':label}</span></button>`).join('');}
function guideCard(g){return `<div class="guide-card soft-card"><img src="${guideImg(g)}" alt="${esc(g.title)}"><div class="guide-scrim"></div><div class="guide-content"><small>小忆问 · ${esc(g.source)}</small><h2>${esc(g.title)}</h2><p>“${esc(g.q)}”</p><div class="guide-actions"><button data-final="guide-record">讲这个话题</button><button data-final="guide-next">换一个 ›</button></div></div></div>`;}
function finalHome(){const g=GUIDES[state.guideIndex];const featured=people.slice(0,3);const photoGuides=GUIDES.filter(x=>x.source.includes('拍照')||x.source.includes('上传'));return `<section class="screen final-home"><div class="topline"><span class="eyebrow">陈建华 · 我的回忆</span><button class="tiny-action" data-route="books">我的书 ›</button></div><h1 class="hello">今天，想从哪里<br>开始讲？</h1><button class="direct-record" data-final="agent-demo-record"><span class="mic-orb">●</span><span><strong>直接开讲</strong><small>录一段，看小忆整理成文稿</small></span><b>›</b></button>${guideCard(g)}<div class="section-head"><h2>他们想听的故事</h2><button data-route="people">人物关系 ›</button></div><div class="people-strip home-people-three">${featured.map(p=>`<button class="person-card" data-person="${p.id}">${avatar(p)}<span class="name">${p.name}</span><span class="rel">${p.rel}</span><div class="counts">${p.question.length} 条提问 · ${activeRecords(p).length} 条语音</div>${unreadCount(p)?'<i class="unread-dot"></i>':''}</button>`).join('')}</div><div class="section-head"><h2>从已有线索聊起</h2><button data-final="all-guides">全部话题 ›</button></div><div class="clue-grid">${photoGuides.slice(0,4).map(x=>`<button data-final="select-guide" data-id="${x.id}"><img src="${guideImg(x)}" alt=""><small>${esc(x.source)}</small><strong>${esc(x.title)}</strong></button>`).join('')}</div></section>`;}
function allGuidesPage(){return `<section class="screen subscreen">${headerBack('讲述')}<span class="eyebrow">小忆准备的话题</span><h1 class="subheading">从想说的那一件开始</h1><p class="subtext">线索只用来选话题，经过仍由你来讲。</p>${assistantMini('guides','你想从哪一张照片或哪一件小事说起？')}${['默认话题','本人拍照','协作端上传'].map(group=>`<div class="section-head"><h2>${group}</h2></div>${GUIDES.filter(g=>group==='默认话题'?g.source==='默认话题':group==='本人拍照'?g.source.includes('本人'):g.source.includes('协作')||g.source.includes('思远')).map(g=>`<button class="guide-row" data-final="select-guide" data-id="${g.id}"><img src="${guideImg(g)}" alt=""><span><small>${esc(g.source)}</small><strong>${esc(g.title)}</strong><em>“${esc(g.q)}”</em></span><b>›</b></button>`).join('')}`).join('')}<div class="method-card soft-card"><strong>小忆怎样问</strong><p>先听你讲完，再按线索选方向，一次只问一个问题。协作内容不会直接写进正文。</p><button data-final="ai-open" data-context="guides">和小忆聊聊 ›</button></div></section>`;}
function finalStories(){if(state.storiesView==='timeline')return finalTimeline();const vis=EVENTS.filter(e=>!state.deletedStories.includes(e.id));return `<section class="screen"><div class="topline"><span class="eyebrow">我的经历</span><button class="tiny-action" data-final="upload-sheet">＋ 添加内容</button></div><h1 class="subheading">说过的，都在这里</h1><p class="subtext">${vis.length} 件经历 · ${vis.reduce((n,e)=>n+e.segments.length,0)+state.added.length} 段语音</p>${assistantMini('stories','你要补充哪一个片段？')}<div class="view-switch"><button class="selected" data-extra="stories-list">故事列表</button><button data-extra="stories-timeline">照片时间轴</button></div>${[...new Set(vis.map(e=>e.period))].map(period=>`<div class="section-head"><h2>${period}</h2></div>${vis.filter(e=>e.period===period).map(eventCard).join('')}`).join('')}<div style="height:18px"></div><button class="primary green full" data-action="record">讲一段新的经历</button></section>`;}
function finalTimeline(){const m=memories[state.memoryIndex];return `<section class="screen timeline-final"><div class="topline"><span class="eyebrow">经历 · 照片时间轴</span><button class="tiny-action" data-final="upload-sheet">＋ 照片</button></div><h1 class="subheading">沿着照片，走过这些年</h1>${assistantMini('timeline','停在一张照片上，我陪你想起那一天。')}<div class="view-switch"><button data-extra="stories-list">故事列表</button><button class="selected" data-extra="stories-timeline">照片时间轴</button></div><div class="timeline-stage"><div class="timeline-track" id="photo-stream">${memories.map((x,i)=>`<button class="timeline-photo ${i===state.memoryIndex?'active':''}" data-final="focus-memory" data-id="${i}"><img src="${memImg(x)}" alt="${esc(x.title)}"><span>${esc(x.year)}</span></button>`).join('')}</div></div><div class="timeline-years">${memories.map((x,i)=>`<button class="${i===state.memoryIndex?'active':''}" data-final="focus-memory" data-id="${i}">${esc(x.year)}</button>`).join('')}</div><div id="timeline-story">${finalMemoryText(m)}</div><div class="timeline-actions"><button class="ghost" data-final="timeline-play">▶ 听片段</button><button class="ghost" data-final="timeline-text">查看文字</button><button class="primary green" data-action="record-memory">补充讲述</button></div></section>`;}
function finalMemoryText(m){const p=person(m.person);return `<div class="timeline-story soft-card"><small>${esc(m.date)} · ${esc(m.place)}</small><h2>${esc(m.title)}</h2><p>${esc(m.story)}</p></div>${p?`<button class="timeline-person" data-person="${p.id}">${avatar(p,37)}<span><strong>${p.name}</strong><small>${p.rel} · 与这段经历有关</small></span><b>›</b></button>`:''}`;}
function coverVisual(b){const img=b.id==='life'?'narrator':b.id==='work'?'workshop':'huangshan';return `<div class="cover-design cover-${b.id}"><img src="${asset(img)}" alt=""><div class="cover-overlay"><small>${b.id==='life'?'陈建华 · 口述自传':b.id==='work'?'华辰二十六年':'山河与家人'}</small><strong>${esc(b.title)}</strong><span>陈建华　著</span></div></div>`;}
function finalBooks(){return `<section class="screen bookshelf-final"><div class="topline"><span class="eyebrow">我的回忆册</span><button class="tiny-action" data-extra="new-book">＋ 新建</button></div><h1 class="subheading">我的书架</h1>${assistantMini('books','想把哪一段经历放进书里？')}<div class="shelf-top"></div><div class="book-shelf">${books.map(b=>`<button class="shelf-book book-${b.id}" data-book="${b.id}">${coverVisual(b)}<span>${esc(b.title)}</span></button>`).join('')}</div><div class="shelf-bottom"></div><div class="section-head"><h2>继续制作</h2></div><div class="make-actions"><button data-extra="new-book">＋ 制作新版本</button><button data-final="order-open" data-id="life">选择成品与册数</button><button data-extra="export" data-id="life">导出电子稿</button></div><div class="section-head"><h2>最近的页</h2></div><button class="timeline-peek" data-book="life"><img src="${asset('father')}" alt="父亲的照片"><div><small>人生故事 · 第一章</small><strong>木匠父亲的工作台</strong><span>刨花味，我现在还记得</span></div><b>›</b></button></section>`;}
function myPage(){return finalBooks().replace('<span class="eyebrow">我的回忆册</span>','<span class="eyebrow">我的空间</span>').replace('<h1 class="subheading">我的书架</h1>',`<div class="my-title-row"><h1 class="subheading">我的</h1><button class="my-follow-inline" data-final="my-follow"><span class="follow-faces"><img src="${asset('community-yuzhen')}" alt=""><img src="${asset('community-jianguo')}" alt=""><img src="${asset('pro-shen')}" alt=""></span><strong>我的关注</strong><b>›</b></button></div><div class="section-head"><h2>我的书架</h2></div>`)}
const FOLLOW_NEWS=[
 {id:'photo',pro:'shen',title:'翻旧照片时，先听他讲“画面外”的事',text:'一张照片不只记着拍摄的那一秒。陪长辈看照片时，我常先请他看看背景里的一处小物件，再等他自己把那天讲完整。',date:'9月15日'},
 {id:'voice',pro:'lin',title:'一段原声怎样留在书页上',text:'书可以重新排版，讲述人的停顿、重复和一句很口语的话却值得留着。读者听到原声时，往往能认出家里那个熟悉的人。',date:'9月12日'},
 {id:'chapter',pro:'chen',title:'整理一段工作回忆，从场景开始',text:'比起先问“你最成功的一次是什么”，我更愿意问第一次到现场时看见了什么。人物、物件和声音出现后，故事会自己往前走。',date:'9月8日'}
];
function followPage(){return `<section class="screen subscreen follow-page">${headerBack('我的')}<h1 class="subheading">我的关注</h1><div class="section-head"><h2>互关好友</h2></div>${COMMUNITY.slice(0,2).map(n=>`<button class="follow-person" data-final="friend-open" data-id="${n.id}"><img src="${asset(n.avatar)}" alt="${esc(n.name)}头像"><span><strong>${esc(n.name)}</strong><small>互相关注 · 可以分享回忆册</small></span><b>对话 ›</b></button>`).join('')}<div class="section-head"><h2>关注的访谈者</h2></div>${PROS.filter(p=>p.id==='shen'||p.id==='lin').map(p=>`<button class="follow-person" data-extra="pro" data-id="${p.id}"><img src="${asset(p.avatar)}" alt="${esc(p.name)}头像"><span><strong>${esc(p.name)}</strong><small>${esc(p.title)} · ${p.live?'正在直播':'新内容'}</small></span><b>主页 ›</b></button>`).join('')}<div class="section-head"><h2>他们最近写的</h2></div>${FOLLOW_NEWS.map(n=>{const p=PROS.find(x=>x.id===n.pro);return `<button class="news-card" data-final="news-open" data-id="${n.id}"><img src="${asset(p.avatar)}" alt=""><span><small>${p.name} · ${n.date}</small><strong>${esc(n.title)}</strong><em>${esc(n.text)}</em></span><b>›</b></button>`}).join('')}</section>`;}
function friendPage(){const n=COMMUNITY.find(x=>x.id===state.followFriend)||COMMUNITY[0];return `<section class="screen subscreen friend-page">${headerBack('我的关注')}<div class="friend-head"><img src="${asset(n.avatar)}" alt="${esc(n.name)}头像"><span><strong>${esc(n.name)}</strong><small>互相关注 · 本地对话预览</small></span></div><div class="friend-bubbles"><div class="friend-bubble"><small>${esc(n.name)}分享了回忆册</small>${communityBook(n)}<p>“这本书里有我在车间那几年，你有空翻翻。”</p></div>${state.friendMessages.filter(m=>m.to===n.id).map(m=>`<div class="friend-bubble mine"><small>我分享给${esc(n.name)}</small><p>${esc(m.text)}</p></div>`).join('')}</div><div class="section-head"><h2>分享我的书</h2></div><div class="friend-books">${books.slice(0,3).map(b=>`<button data-final="friend-share-book" data-id="${b.id}">${coverVisual(b)}<strong>${esc(b.title)}</strong></button>`).join('')}</div><form id="friend-text-form" class="ai-compose"><input name="text" maxlength="180" placeholder="写一句想说的话…" required><button type="submit">保存</button></form><p class="ai-note">这里只展示互相分享的交互方式，不会发送给真实好友。</p></section>`;}
function newsPage(){const n=FOLLOW_NEWS.find(x=>x.id===state.followNews)||FOLLOW_NEWS[0],p=PROS.find(x=>x.id===n.pro);return `<section class="screen subscreen">${headerBack('我的关注')}<div class="news-author"><img src="${asset(p.avatar)}" alt="${p.name}头像"><span><strong>${p.name}</strong><small>${p.title} · ${n.date}</small></span></div><h1 class="subheading">${esc(n.title)}</h1><p class="news-body">${esc(n.text)}</p><button class="primary green full" data-extra="pro" data-id="${p.id}">查看${p.name}的服务</button></section>`;}
function editedPage(b,i){const p=b.pages[i];return p?{...p,text:pageEdits[`${b.id}-${i}`]??p.text}:null;}
function spreadPageContent(b,i,side){const p=editedPage(b,i);if(!p)return `<div class="spread-page blank-page"><span>· ${esc(b.title)} ·</span></div>`;return `<button class="spread-page spread-${b.id} ${side}" data-final="page-full" data-id="${i}"><small>${esc(p.label||b.kind)}</small>${p.photo?`<img src="${asset(p.photo)}" alt="${esc(p.title)}">`:''}<h3>${esc(p.title)}</h3><p>${esc(p.text||p.subtitle||'')}</p><i>${i+1}</i><em>点开阅读和编辑</em></button>`;}
const BOOK_PROG={life:[62,'已收录 12 段原声 · 约完成六成'],work:[40,'已收录 6 段原声 · 第二章制作中'],travel:[18,'已收录 2 段原声 · 刚开始']};
function finalReader(){const b=books.find(x=>x.id===state.bookId)||books[0];const closed=state.pageIndex===0;const left=state.pageIndex,right=left+1;const bp=BOOK_PROG[b.id]||[10,''];return `<section class="screen subscreen reader-final">${headerBack('我的书架')}<div class="book-reader-head"><small>${esc(b.kind)}</small><h1>${esc(b.title)}</h1><div class="reader-prog"><i style="width:${bp[0]}%"></i></div><p class="reader-prog-t">${bp[1]} · 完成 ${bp[0]}%</p></div>${assistantMini('reader','这一页里，有没有你想补充的原话？')}${closed?`<button class="closed-book" data-final="open-book">${coverVisual(b)}<span>翻开 ›</span></button>`:`<div class="spread-shell" id="spread-shell"><div class="spread-gutter"></div>${spreadPageContent(b,left,'left')}${spreadPageContent(b,right,'right')}</div>`}<div class="reader-controls"><button data-final="spread-prev" ${closed?'disabled':''}>‹ 上一页</button><span>${closed?'封面':`${left+1}–${Math.min(right+1,b.pages.length)} / ${b.pages.length}`}</span><button data-final="${closed?'open-book':'spread-next'}" ${!closed&&right>=b.pages.length-1?'disabled':''}>下一页 ›</button></div><div class="reader-extra"><button class="ghost" data-extra="export" data-id="${b.id}">导出电子稿</button><button class="primary" data-final="order-open" data-id="${b.id}">制作成品</button></div></section>`;}
function sentenceSpans(text){return String(text||'').split(/(?<=[。！？\n])/).filter(x=>x.trim()).map((s,i)=>`<span class="reader-segment ${state.readIndex===i?'reading':''}" data-sentence="${i}">${esc(s)}</span>`).join('');}
function pageQuestions(p){const text=String(p.text||'');if(/黄先生|出口订单|广交会/.test(text))return {detail:'你说的那个黄先生，你记得他全名吗？',scene:'你说拿计算器比划，那个计算器是什么样的？'};if(/父亲|工作台|木匠/.test(text))return {detail:'你提到父亲的工作台，它以前放在屋里的哪一处？',scene:'父亲做木工时，哪一种声音你现在还记得？'};if(/美凤/.test(text))return {detail:'说到美凤，你还想补充你们一起做过的哪件小事？',scene:'那一天周围是什么样，你还记得吗？'};return {detail:'这一页里提到的人，你还想补充哪一个细节？',scene:'这件事发生时，周围哪个画面你还记得？'};}
function fullPage(){const b=books.find(x=>x.id===state.bookId)||books[0],i=state.fullPageIndex,p=editedPage(b,i);if(!p)return finalReader();const key=`${b.id}-${i}`,qs=pageQuestions(p),q=qs[state.pageAiQuestion]||qs.detail,note=state.pageNotes[key]||'';return `<section class="screen subscreen fullpage-final">${headerBack(b.title)}<div class="fullpaper fullpaper-${b.id}"><small>${esc(p.label||b.kind)}</small>${p.photo?`<img src="${asset(p.photo)}" alt="${esc(p.title)}">`:''}<h1>${esc(p.title)}</h1>${state.inlineEditing?`<div class="fullpaper-text editing" id="fullpaper-edit" contenteditable="true" aria-label="编辑本页文字">${esc(p.text||'')}</div>`:`<div class="fullpaper-text" id="fullpaper-text">${sentenceSpans(p.text||p.subtitle)}</div>`}<span class="fullpaper-number">${i+1}</span></div><div class="fullpage-actions"><button data-final="${state.inlineEditing?'save-page-edit':'edit-page'}">${state.inlineEditing?'保存':'编辑本页'}</button><button data-final="read-page">${state.readIndex>=0?'停止朗读':'▶ 朗读本页'}</button></div><p class="subtext">朗读时正在读的句子会标记在书页上。</p>${xySay(`“${esc(q)}”`,`<button class="xy-chip ${state.pageAiQuestion==='detail'?'sel':''}" data-final="page-question" data-id="detail">补人物或物件</button><button class="xy-chip ${state.pageAiQuestion==='scene'?'sel':''}" data-final="page-question" data-id="scene">补一个场景</button><button class="xy-chip" data-final="page-question-speak">▶ 听问题</button><button class="xy-chip" data-final="page-record"><img src="assets/ic-mic.png" alt="">语音回答</button>`)}<form id="page-ai-form" class="page-ai-compose"><input name="reply" maxlength="350" value="${esc(note)}" placeholder="也可以打字告诉她…"><button type="submit">记到边注</button></form>${note?`<p class="page-note-saved">已记在第 ${i+1} 页的边注里。</p>`:''}</section>`;}
function editPage(){const b=books.find(x=>x.id===state.bookId),i=state.fullPageIndex,p=editedPage(b,i);return `<section class="screen subscreen">${headerBack(b.title)}<span class="eyebrow">编辑第 ${i+1} 页</span><h1 class="subheading">${esc(p.title)}</h1><p class="subtext">改动只保存到当前浏览器的预览书页。</p><form id="final-edit-form" class="full-form"><label>这一页的文字<textarea name="text" maxlength="1400" required>${esc(p.text||'')}</textarea></label><button class="primary full" type="submit">保存这一页</button></form></section>`;}
function filePage(){return `<section class="screen subscreen">${headerBack('上传内容')}<span class="eyebrow">文件线索</span><h1 class="subheading">存下一份旧文件</h1><p class="subtext">旧订单、证件、手写记录都可先存下；小忆只据此选话题，正文由你确认。</p><form id="final-file-form" class="full-form"><label>选择文件<input name="file" type="file" accept=".pdf,.doc,.docx,.txt,.jpg,.jpeg,.png" required></label><label>这是什么文件<input name="title" maxlength="40" required placeholder="如：2001 年的第一份出口订单"></label><label>线索说明<textarea name="note" maxlength="240" placeholder="可记下谁提供、日期是否确定"></textarea></label><button class="primary full" type="submit">保存文件线索</button></form><div class="section-head"><h2>已保存的文件</h2></div>${state.addedFiles.map(f=>`<div class="file-row"><span class="file-icon">▤</span><span><strong>${esc(f.title)}</strong><small>${esc(f.name)} · ${esc(f.note||'待本人确认')}</small></span><button data-final="file-delete" data-id="${f.id}">删除</button></div>`).join('')||'<div class="empty">还没有保存文件。</div>'}</section>`;}
openAudioDb=function(){return new Promise((resolve,reject)=>{const req=indexedDB.open('memo-prototype-audio',3);req.onupgradeneeded=()=>{for(const name of ['clips','photos','files'])if(!req.result.objectStoreNames.contains(name))req.result.createObjectStore(name)};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})};
async function putEvidenceFile(id,file){try{const db=await openAudioDb(),tx=db.transaction('files','readwrite');tx.objectStore('files').put(file,id);await new Promise((ok,no)=>{tx.oncomplete=ok;tx.onerror=no});db.close();return true}catch{return false}}
async function deleteEvidenceFile(id){try{const db=await openAudioDb(),tx=db.transaction('files','readwrite');tx.objectStore('files').delete(id);db.close()}catch{}}
const formats=[['hard','精装实体册',128],['soft','平装实体册',79],['mini','照片小册',59],['pdf','电子 PDF 版',49],['audio','有声阅读版',68],['bundle','实体册 + 电子版',158]];
function finalOrder(){const b=books.find(x=>x.id===state.orderBook)||books[0],f=formats.find(x=>x[0]===state.finalFormat)||formats[0],qty=Math.max(1,Math.min(99,Number(state.orderQty)||1));return `<section class="screen subscreen order-final">${headerBack('我的')}<span class="eyebrow">《${esc(b.title)}》</span><h1 class="subheading">选择你的成品</h1>${assistantMini('order','想把这本书做成几册，送给谁？')}<div class="section-head"><h2>版本</h2></div>${formats.map(x=>`<button class="option-row ${x[0]===state.finalFormat?'selected':''}" data-final="order-format" data-id="${x[0]}"><span><strong>${x[1]}</strong><small>${x[0]==='audio'?'朗读段落与声音标记':x[0]==='pdf'?'电子文件':x[0]==='mini'?'轻巧照片装帧':'纸张与装帧预览'}</small></span><b>¥${x[2]}</b></button>`).join('')}<div class="section-head"><h2>数量</h2></div><div class="qty-field"><button data-final="qty-minus">−</button><input id="order-qty" type="number" min="1" max="99" value="${qty}" aria-label="购买数量"><button data-final="qty-plus">＋</button></div><div class="price-total soft-card"><span>${f[1]} · ${qty} 份</span><strong>¥${f[2]*qty}</strong></div><button class="primary full" data-final="save-final-order">保存制作方案</button></section>`;}
function uploadOverlay(){return `<div class="upload-shade" data-final="close-upload"><div class="upload-sheet" role="dialog" aria-label="添加内容"><div class="sheet-handle"></div><h2>添加一段线索</h2><p>先存进素材，不会直接写进正文。</p><div class="upload-options"><button data-final="upload-photo"><span class="app-icon ill"><img src="assets/ic-camera.png" alt=""></span><span><strong>照片</strong><small>拍照、相册，或修复老照片</small></span>›</button><button data-final="upload-wechat"><span class="app-icon ill"><img src="assets/ic-wechat.png" alt=""></span><span><strong>聊天记录</strong><small>粘贴微信里的摘录</small></span>›</button><button data-final="upload-file"><span class="app-icon ill"><img src="assets/ic-doc.png" alt=""></span><span><strong>旧文件</strong><small>订单、证件或手写纸</small></span>›</button></div><button class="sheet-cancel" data-final="close-upload">取消</button></div></div>`;}
function aiQuestion(){const g=GUIDES[state.guideIndex];const by={home:g.q,guides:g.q,stories:'你刚刚说的那段经历，最想补充哪一个细节？',timeline:'看着这张照片，你先想起当天的哪个画面？',people:'说到这个人，你最先想起你们一起做过的哪件事？',person:`说到${person(state.personId)?.name||'他'}，你先想起你们一起做过的哪件事？`,community:'听完这个故事，你想到自己的哪一段经历？',books:'这本书里，有哪一页是你最想先讲给家人听的？',reader:'翻到这一页，你还有什么想补充的？',page:'这一页里，有哪个细节你想自己再说一遍？',order:'这本书想送给谁？你最想让他先看到哪一页？'};return by[state.aiContext]||g.q;}
function peopleFinal(){return peoplePage().replace('<div class="topline">',headerBack('首页')+'<div class="topline">').replace('<div class="relation-map">',assistantMini('people','你想先说起故事里的哪一个人？')+'<div class="relation-map">')}
function personFinal(){const p=person(state.personId);return personPage().replace('<div class="profile-hero">',assistantMini('person',`说到${p?.name||'他'}，你先想起哪一件事？`)+'<div class="profile-hero">')}
function recordFinal(){return recordPage()}
const LIVE_TRANSCRIPT=[
 ['这张照片啊，是零一年广交会。','我们第一次去参加。'],
 ['展位是最小的那种，三米乘三米。','我带了两个样品箱，自己扛进去的。'],
 ['那天来了一个马来西亚的客户。','他问了几个技术参数，留了一张名片。'],
 ['我英文不行，就拿计算器跟他比划价格。','后来他给了我们第一张出口订单。'],
 ['三万美金，我高兴得一晚上没睡。','那时候对我是一笔很大的钱。'],
 ['交货那天我自己去了码头。','看着集装箱装上船，心里说不出什么感觉。']
];
function liveTranscriptLines(sec=0){const pair=LIVE_TRANSCRIPT[Math.floor(sec/3)%LIVE_TRANSCRIPT.length];return `<span>${esc(pair[0])}</span><span>${esc(pair[1])}<i class="typing-cursor"></i></span>`;}
window.updateLiveTranscript=function(sec){const box=document.querySelector('#live-transcript-lines');if(box)box.innerHTML=liveTranscriptLines(sec)};
recordFinal=function(){const p=state.recordFor?person(state.recordFor):null,q=state.recordTitle||`今天你最想先讲${p?'和'+p.name+'有关的':'的'}哪件事？`;return `<section class="screen subscreen record-final ios-record-screen">${headerBack('讲一段故事')}<div class="record-question"><img src="${asset('xiaoyi')}" alt="小忆头像"><span><small>小忆问</small><strong>“${esc(q)}”</strong></span><button data-final="record-question-speak" aria-label="朗读问题">▶</button></div><h1 class="subheading">${p?`和${p.name}有关的故事`:'把这段经历讲下来'}</h1><div class="record-panel"><div class="record-orb ${state.recording?'':'paused'}">${state.recording?'◉':'<img class="orb-mic" src="assets/ic-mic.png" alt="">'}</div><div class="wave ${state.recording?'':'still'}">${Array.from({length:21},(_,i)=>`<i style="--h:${14+(i*17)%54}px;--d:${(i%7)*-0.13}s"></i>`).join('')}</div><div class="record-time">${formatSecs(state.recordSeconds)}</div>${state.recording?`<div class="record-transcript live-transcript"><small>正在形成文字</small><p id="live-transcript-lines">${liveTranscriptLines(state.recordSeconds)}</p></div>`:'<p class="record-help">点按按钮，开始记录这段讲述。</p>'}<div class="record-actions">${state.recording?'<button class="ghost" data-action="pause-record">暂停</button><button class="primary" data-action="finish-record">完成录制</button>':'<button class="primary full" data-action="start-record">开始录下我的原声</button>'}</div></div></section>`};
const AGENT_RAW='这张照片啊，是零一年……嗯……广交会。我们第一次去参加。展位是最小的那种，三米乘三米，在角落里。我带了两个样品箱，自己扛进去的。嗯……那天来了一个马来西亚的客户，华裔，姓黄。他看了看我们的产品，问了几个技术参数，嗯，留了一张名片。我当时英文不行，拿个计算器跟他比划价格。后来这个黄先生给了我们第一张出口订单，三万美金。我高兴得一晚上没睡。三万美金，那时候对我是一笔很大的钱。交货那天我自己去码头，就站在那里看着集装箱装上去，心里说不出是什么感觉。合同签完我没敢告诉国平，怕他以为我在吹牛。等货真的装上了船，我才跟他说。他愣了一下，然后笑了，说行啊老陈。那个黄先生后来跟了我们十几年。每年他来中国我都请他吃饭。他不会用筷子，每次都让我教他，但他每次都学不会。';
const AGENT_CLEAN='这张照片啊，是零一年广交会。我们第一次去参加。展位是最小的那种，三米乘三米，在角落里。我带了两个样品箱，自己扛进去的。那天来了一个马来西亚的客户，华裔，姓黄。他看了看我们的产品，问了几个技术参数，留了一张名片。我当时英文不行，拿个计算器跟他比划价格。后来这个黄先生给了我们第一张出口订单，三万美金。我高兴得一晚上没睡。三万美金，那时候对我是一笔很大的钱。交货那天我自己去码头，就站在那里看着集装箱装上去，心里说不出是什么感觉。合同签完我没敢告诉国平，怕他以为我在吹牛。等货真的装上了船，我才跟他说。他愣了一下，然后笑了，说行啊老陈。那个黄先生后来跟了我们十几年。每年他来中国我都请他吃饭。他不会用筷子，每次都让我教他，但他每次都学不会。';
const AGENT_QUESTIONS={person:'你说的那个黄先生，你记得他全名吗？',timeline:'你说黄先生给了你们订单——是展会那天就谈妥了，还是后来又联系的？',chapter:'从展会上认识到拿到订单，这中间还有哪一步是你想留在书里的？'};
function demoRecordPage(){return `<section class="screen subscreen agent-record ios-record-screen">${headerBack('讲述')}<span class="eyebrow">展会照片 · 工作回忆第二章</span><div class="record-question"><img src="${asset('xiaoyi')}" alt="小忆头像"><span><small>小忆问</small><strong>“看着这张合影，你记得那天是怎么开始的吗？”</strong></span><button data-final="demo-question-speak" aria-label="朗读问题">▶</button></div><button class="agent-why" data-final="agent-why">为什么这样问？ ›</button>${state.agentWhy?'<div class="agent-reason soft-card">照片给了话题方向。思远标注的“2001 年广交会”还没有由你确认，所以小忆没有把它放进问题里。</div>':''}<div class="record-panel"><div class="record-orb ${state.demoRecording?'':'paused'}">${state.demoRecording?'◉':'<img class="orb-mic" src="assets/ic-mic.png" alt="">'}</div><div class="wave ${state.demoRecording?'':'still'}">${Array.from({length:21},(_,i)=>`<i style="--h:${14+(i*17)%54}px;--d:${(i%7)*-0.13}s"></i>`).join('')}</div><div class="record-time">${formatSecs(state.demoSeconds)}</div>${state.demoRecording?`<div class="record-transcript live-transcript"><small>正在形成文字</small><p id="live-transcript-lines">${liveTranscriptLines(state.demoSeconds)}</p></div>`:'<p class="record-help">点按按钮，开始记录这段讲述。</p>'}<div class="record-actions">${state.demoRecording?'<button class="primary full" data-final="demo-finish">完成录制</button>':'<button class="primary full" data-final="demo-start">开始录下我的原声</button>'}</div></div></section>`;}
function agentReviewPage(){return `<section class="screen subscreen agent-review">${headerBack('讲述')}<span class="eyebrow">事件标题 · 工作回忆第二章</span><h1 class="subheading">华辰第一个出口订单</h1><div class="agent-state"><span>原声 → 整理 → 本人确认</span><strong>${state.agentConfirmed?'已确认':'待你确认'}</strong></div><div class="draft-switch"><button data-final="draft-clean" class="${state.agentRaw?'':'selected'}">整理后的完整文稿</button><button data-final="draft-raw" class="${state.agentRaw?'selected':''}">看原文</button></div><div class="agent-draft soft-card"><small>${state.agentRaw?'原始逐字稿 · 保留停顿与重复':'纠错并整理后的文稿 · 默认显示'}</small><p>${esc(state.agentRaw?AGENT_RAW:AGENT_CLEAN)}</p></div><div class="agent-decisions soft-card"><strong>小忆这样整理</strong><p>去掉三个没有信息的“嗯”；“三万美金”说了两次，都保留；“零一年”仍用你的说法。国平补充的月份只放在待确认边注里。</p><div class="uncertain-note"><small>待确认</small><span>你说：零一年<br>国平补充：2001 年春交会</span></div></div>${!state.agentConfirmed?`<div class="review-actions"><button data-final="draft-read">▶ 朗读文稿</button><button data-final="agent-confirm">是，就这样</button></div><button class="tiny-action" data-final="draft-raw" style="width:100%">再看一次原文</button>`:`<div class="agent-followup"><div class="followup-person xy-look"><img src="${asset('xiaoyi')}" alt="小忆头像"><span><small>小忆 · 只补一个问题，也可以直接保存</small><strong>“${AGENT_QUESTIONS[state.agentQuestion]}”</strong></span></div><div class="followup-options three"><button data-final="followup-select" data-id="person" class="${state.agentQuestion==='person'?'selected':''}">补人物</button><button data-final="followup-select" data-id="timeline" class="${state.agentQuestion==='timeline'?'selected':''}">补时间线</button><button data-final="followup-select" data-id="chapter" class="${state.agentQuestion==='chapter'?'selected':''}">补章节空白</button></div><form id="agent-supplement-form" class="full-form"><label>想补充的话<textarea name="supplement" maxlength="350" placeholder="想起来就讲；不想补也可以跳过">${esc(state.agentSupplement)}</textarea></label><button class="ghost" type="submit">先记在边注</button></form>${state.agentSupplement?'<p class="supplement-saved">这句补充已放在边注；正文仍保留刚确认的原话。</p>':''}<button class="primary green full" data-final="agent-save">保存这件经历</button><button class="tiny-action" data-final="agent-save" style="width:100%;margin-top:10px">今天先不补充，直接保存</button></div>`}</section>`;}
function agentDonePage(){return `<section class="screen subscreen agent-done">${headerBack('讲述')}<div class="success-orb">✓</div><h1 class="subheading">华辰第一个出口订单</h1><p class="subtext">这段经历已经按你确认的说法收好了。</p>${xySay('今天先到这里，还是再录一段？',`<button class="xy-chip" data-final="agent-rest">回到首页</button><button class="xy-chip sel" data-final="agent-more"><img src="assets/ic-mic.png" alt="">再录一段</button>`)}</section>`;}
function aiPage(){const q=aiQuestion();return `<section class="screen subscreen ai-page">${headerBack('小忆')}<div class="ai-profile"><img src="${asset('xiaoyi')}" alt="小忆头像"><span><strong>小忆</strong><small>温和的访谈者 · 语音优先</small></span><i></i></div><div class="ai-dialogue"><div class="ai-bubble"><small>小忆</small><p>${esc(q)}</p><button data-final="ai-speak">▶ 听问题</button></div>${state.aiMessages.slice(-6).map(m=>`<div class="ai-bubble ${m.from==='me'?'mine':''}"><small>${m.from==='me'?'我':'小忆'}</small><p>${esc(m.text)}</p></div>`).join('')}</div><div class="ai-examples"><button data-final="ai-example" data-id="那一年我第一次出省跑业务。">第一次跑业务</button><button data-final="ai-example" data-id="我想从一张老照片说起。">从老照片说起</button><button data-final="ai-example" data-id="我还没想好，先听一个问题。">换个问题</button></div><form id="ai-text-form" class="ai-compose"><input name="message" maxlength="350" placeholder="也可以先打字告诉小忆…" aria-label="给小忆的文字"><button type="submit">发送</button></form><div class="ai-voice-actions"><button data-final="ai-listen"><img class="opt-ic" src="assets/ic-mic.png" alt="">语音对话</button><button data-final="ai-record">录一段故事</button></div><p class="ai-note">对话为本地演示。正式录音时，小忆安静聆听。</p></section>`;}
let timelineTimer=null,recognizer=null,readingUtterance=null;
function finalRender(){syncPhotoGuides();syncEvidenceGuides();clearInterval(timelineTimer);timelineTimer=null;const pages={home:finalHome,stories:finalStories,people:peopleFinal,person:personFinal,audioall:audioAllPage,community:communityPage,'community-detail':communityDetail,'pro-detail':proDetail,books:myPage,follow:followPage,friend:friendPage,news:newsPage,reader:finalReader,fullpage:fullPage,editpage:editPage,order:finalOrder,'order-done':orderDonePage,'new-book':newBookPage,photo:photoPage,photoform:photoFormPage,chat:chatPage,file:filePage,guides:allGuidesPage,ai:aiPage,topic:topicPage,ready:readyPage,record:recordFinal,'agent-demo-record':demoRecordPage,'agent-review':agentReviewPage,'agent-done':agentDonePage,preview:previewWithActions,'record-done':recordDonePage};const fn=pages[state.route]||finalHome;viewport.innerHTML=fn()+(state.deleteId?dialog():'')+(state.storySegment?segmentSheet():'')+(state.storyDelete?confirmStorySheet():'')+(state.uploadSheet?uploadOverlay():'');const main=['home','stories','community','books'].includes(state.route);tabbar.innerHTML=main?finalTabs():'';tabbar.classList.toggle('hidden',!main);if(state.route==='stories'&&state.storiesView==='timeline'){setTimeout(()=>focusTimeline(false),40);timelineTimer=setInterval(()=>{if(!state.timelinePaused){state.memoryIndex=(state.memoryIndex+1)%memories.length;focusTimeline(true)}},4000)}}
render=finalRender;
back=function(){if(state.uploadSheet){state.uploadSheet=false;return render()}if(state.route==='ai')return route(state.aiOrigin||'home');if(state.route==='agent-review')return route('agent-demo-record');if(state.route==='agent-done')return route('home');if(state.route==='agent-demo-record')return route('home');if(state.route==='friend'||state.route==='news')return route('follow');if(state.route==='follow')return route('books');if(state.route==='fullpage')return route('reader');if(state.route==='editpage')return route('fullpage');if(state.route==='guides')return route('home');if(state.route==='people')return route('home');if(state.route==='person')return route(state.personFrom&&state.personFrom!=='person'?state.personFrom:'people');if(state.route==='reader')return route('books');if(state.route==='order')return route('books');if(state.route==='file')return route('home');return sourceBack()};
function focusTimeline(animate){const track=$('#photo-stream');if(!track)return;const cards=[...track.children],card=cards[state.memoryIndex];if(card){track.scrollTo({left:card.offsetLeft-track.offsetLeft-track.clientWidth/2+card.clientWidth/2,behavior:animate?'smooth':'instant'});cards.forEach((c,i)=>c.classList.toggle('active',i===state.memoryIndex))}$('#timeline-story')?.replaceChildren();if($('#timeline-story'))$('#timeline-story').innerHTML=finalMemoryText(memories[state.memoryIndex]);document.querySelectorAll('.timeline-years button').forEach((x,i)=>x.classList.toggle('active',i===state.memoryIndex))}
function openAi(context){state.aiContext=context||state.route;state.aiOrigin=state.route;route('ai')}
function askAi(value){const text=String(value||'').trim();if(!text)return;state.aiMessages.push({from:'me',text});let response='我听到了。你愿意从那一刻最先浮现在脑海里的画面说起吗？';if(/照片|相册|合影/.test(text))response='看着那张照片，你先注意到的是谁、什么物件，还是当时的场景？';else if(/工作|业务|订单|工厂/.test(text))response='你记得那件事最初是怎么开始的吗？';else if(/还没|想好|换个/.test(text))response='可以先停一停。你想到一个地方、一件旧物或一个人，再告诉我就好。';state.aiMessages.push({from:'ai',text:response});localStorage.setItem('memo-prototype-ai-chat-v1',JSON.stringify(state.aiMessages.slice(-30)));rerenderPreserve()}
function startListening(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return toast('这台浏览器暂不支持语音转文字，可用“录一段故事”保存原声');recognizer?.abort();recognizer=new R();recognizer.lang='zh-CN';recognizer.interimResults=false;recognizer.onresult=e=>askAi(e.results[0][0].transcript);recognizer.onerror=()=>toast('语音识别未完成，请再试一次');recognizer.start();toast('小忆在听，请说话')}
function readFullPage(){if(state.readIndex>=0){speechSynthesis.cancel();state.readIndex=-1;return rerenderPreserve()}const b=books.find(x=>x.id===state.bookId),p=editedPage(b,state.fullPageIndex);const sentences=String(p.text||'').split(/(?<=[。！？\n])/).filter(x=>x.trim());let i=0;function next(){if(i>=sentences.length){state.readIndex=-1;return rerenderPreserve()}state.readIndex=i;document.querySelectorAll('.reader-segment').forEach((x,j)=>x.classList.toggle('reading',j===i));const u=new SpeechSynthesisUtterance(sentences[i]);u.lang='zh-CN';u.rate=.82;u.onend=()=>{i++;next()};u.onerror=()=>{state.readIndex=-1;rerenderPreserve()};readingUtterance=u;speechSynthesis.speak(u)}speechSynthesis.cancel();next();rerenderPreserve()}
document.addEventListener('click',e=>{const el=e.target.closest('[data-final]');if(!el)return;if(e.target.closest('[data-dual]'))return;e.preventDefault();e.stopImmediatePropagation();const a=el.dataset.final,id=el.dataset.id;switch(a){
case 'upload-sheet':state.uploadSheet=true;return render();
case 'close-upload':if(e.target.closest('.upload-sheet')&&!el.matches('[data-final="close-upload"]'))return;state.uploadSheet=false;return render();
case 'upload-camera':case 'upload-album':state.uploadSheet=false;route('photo');setTimeout(()=>{const input=$('#photo-file');if(!input)return;if(a==='upload-camera')input.setAttribute('capture','environment');else input.removeAttribute('capture');input.click()},40);return;
case 'upload-wechat':state.uploadSheet=false;return route('chat');
case 'upload-file':state.uploadSheet=false;return route('file');
case 'upload-photo':state.uploadSheet=false;return route('photo');
case 'agent-demo-record':return route('agent-demo-record');
case 'guide-next':state.guideIndex=(state.guideIndex+1)%GUIDES.length;state.guideChanges++;return rerenderPreserve();
case 'guide-record':return GUIDES[state.guideIndex].id==='expo'?route('agent-demo-record'):openRecord(null,GUIDES[state.guideIndex].q);
case 'all-guides':return route('guides');
case 'select-guide':state.guideIndex=Math.max(0,GUIDES.findIndex(g=>g.id===id));return route('home');
case 'focus-memory':state.memoryIndex=Number(id);state.timelinePaused=true;return focusTimeline(true);
case 'timeline-play':{const m=memories[state.memoryIndex],r=state.added.find(x=>x.title.includes(m.title));if(r)return playAudio(r.id);speakText(m.story);return toast('正在朗读示例文字；自己录入的原声可在经历列表回听')}
case 'timeline-text':return $('#timeline-story')?.scrollIntoView({behavior:'smooth'});
case 'open-book':state.pageIndex=1;return render();
case 'spread-prev':state.pageIndex=Math.max(0,state.pageIndex-2);$('#spread-shell')?.classList.add('turn-prev');return setTimeout(render,500);
case 'spread-next':{const b=books.find(x=>x.id===state.bookId);state.pageIndex=Math.min(b.pages.length-1,state.pageIndex+2);$('#spread-shell')?.classList.add('turn-next');return setTimeout(render,500)}
case 'page-full':state.fullPageIndex=Number(id);state.readIndex=-1;state.inlineEditing=false;return route('fullpage');
case 'edit-page':state.inlineEditing=true;return rerenderPreserve();
case 'save-page-edit':{const el2=document.getElementById('fullpaper-edit');const text=(el2?.innerText||'').trim();if(!text)return toast('这一页还没有文字');pageEdits[`${state.bookId}-${state.fullPageIndex}`]=text;localStorage.setItem('memo-prototype-page-edits-v1',JSON.stringify(pageEdits));state.inlineEditing=false;toast('本页已保存');return rerenderPreserve();}
case 'cancel-page-edit':state.inlineEditing=false;return rerenderPreserve();
case 'read-page':return readFullPage();
case 'page-question':state.pageAiQuestion=id;return rerenderPreserve();
case 'page-question-speak':{const b=books.find(x=>x.id===state.bookId),p=editedPage(b,state.fullPageIndex),qs=pageQuestions(p);return speakText(qs[state.pageAiQuestion]||qs.detail)}
case 'page-record':{const b=books.find(x=>x.id===state.bookId),p=editedPage(b,state.fullPageIndex),qs=pageQuestions(p);return openRecord(null,qs[state.pageAiQuestion]||qs.detail)}
case 'order-open':state.orderBook=id||state.bookId;return route('order');
case 'order-format':state.finalFormat=id;return rerenderPreserve();
case 'qty-minus':state.orderQty=Math.max(1,Number(state.orderQty)-1);return rerenderPreserve();
case 'qty-plus':state.orderQty=Math.min(99,Number(state.orderQty)+1);return rerenderPreserve();
case 'save-final-order':{const b=books.find(x=>x.id===state.orderBook),f=formats.find(x=>x[0]===state.finalFormat);state.orderDraft={title:b.title,format:f[1],qty:`${state.orderQty} 份`,total:f[2]*state.orderQty};return route('order-done')}
case 'ai-open':return openAi(el.dataset.context);
case 'ai-speak':return speakText(aiQuestion());
case 'ai-example':return askAi(id);
case 'ai-listen':return startListening();
case 'ai-record':return openRecord(null,aiQuestion());
case 'record-question-speak':return speakText(state.recordTitle||'今天你最想先讲哪件事？');
case 'demo-question-speak':return speakText('看着这张合影，你记得那天是怎么开始的吗？');
case 'agent-why':state.agentWhy=!state.agentWhy;return rerenderPreserve();
case 'demo-start':state.demoRecording=true;state.demoSeconds=0;clearInterval(state.demoTimer);state.demoTimer=setInterval(()=>{state.demoSeconds++;const x=$('.agent-record .record-time');if(x)x.textContent=formatSecs(state.demoSeconds);window.updateLiveTranscript?.(state.demoSeconds)},1000);return rerenderPreserve();
case 'demo-finish':clearInterval(state.demoTimer);state.demoRecording=false;state.demoSeconds=Math.max(state.demoSeconds,252);state.agentRaw=false;state.agentConfirmed=false;state.agentSupplement='';return route('agent-review');
case 'real-record':clearInterval(state.demoTimer);state.demoRecording=false;return openRecord(null,'看着这张合影，你记得那天是怎么开始的吗？');
case 'draft-clean':state.agentRaw=false;return rerenderPreserve();
case 'draft-raw':state.agentRaw=true;return rerenderPreserve();
case 'draft-read':return speakText(AGENT_CLEAN);
case 'agent-confirm':state.agentConfirmed=true;return rerenderPreserve();
case 'followup-select':state.agentQuestion=id;return rerenderPreserve();
case 'agent-save':state.agentSaved=true;localStorage.setItem('memo-prototype-agent-demo-v1',JSON.stringify({saved:true,supplement:state.agentSupplement}));return route('agent-done');
case 'agent-rest':return route('home');
case 'agent-more':return route('guides');
case 'my-follow':return route('follow');
case 'friend-open':state.followFriend=id;return route('friend');
case 'news-open':state.followNews=id;return route('news');
case 'friend-share-book':{const b=books.find(x=>x.id===id);if(!b)return;state.friendMessages.push({to:state.followFriend,text:`《${b.title}》 · 陈建华的回忆册。想先让你看看这一页。`});localStorage.setItem('memo-prototype-friend-chat-v1',JSON.stringify(state.friendMessages));toast('分享预览已放进本地对话');return rerenderPreserve()}
case 'community-read':{const n=COMMUNITY.find(x=>x.id===id);if(n)speakText(n.text);return}
case 'community-share':{const n=COMMUNITY.find(x=>x.id===id);if(!n)return;if(navigator.share)navigator.share({title:n.title,text:`${n.text} — ${n.name}《${n.title}》`}).catch(()=>{});else copyText(`${n.text} — ${n.name}《${n.title}》`);return}
case 'file-delete':{state.addedFiles=state.addedFiles.filter(x=>x.id!==id);localStorage.setItem('memo-prototype-files-v1',JSON.stringify(state.addedFiles));deleteEvidenceFile(id);const idx=GUIDES.findIndex(g=>g.id===`file-guide-${id}`);if(idx>=0)GUIDES.splice(idx,1);state.guideIndex=0;return rerenderPreserve()}
}});
document.addEventListener('submit',e=>{if(e.target.id==='ai-text-form'){e.preventDefault();askAi(new FormData(e.target).get('message'))}if(e.target.id==='final-edit-form'){e.preventDefault();const text=String(new FormData(e.target).get('text')||'').trim();if(!text)return;pageEdits[`${state.bookId}-${state.fullPageIndex}`]=text;localStorage.setItem('memo-prototype-page-edits-v1',JSON.stringify(pageEdits));state.inlineEditing=false;toast('本页已保存');rerenderPreserve()}if(e.target.id==='page-ai-form'){e.preventDefault();const reply=String(new FormData(e.target).get('reply')||'').trim();if(!reply)return;const key=`${state.bookId}-${state.fullPageIndex}`;state.pageNotes[key]=reply;localStorage.setItem('memo-prototype-page-notes-v1',JSON.stringify(state.pageNotes));state.pageAiReply=reply;toast('已经记在这页的边注');rerenderPreserve()}},true);
document.addEventListener('change',e=>{if(e.target.id==='order-qty'){state.orderQty=Math.max(1,Math.min(99,Number(e.target.value)||1));rerenderPreserve()}},true);
document.addEventListener('submit',async e=>{if(e.target.id!=='final-file-form')return;e.preventDefault();const form=e.target,file=form.querySelector('input[type="file"]')?.files?.[0],data=new FormData(form),title=String(data.get('title')||'').trim(),note=String(data.get('note')||'').trim();if(!file||!title)return;const id=`evidence-${Date.now()}`;if(!await putEvidenceFile(id,file))return toast('文件未能保存，请换一个浏览器重试');state.addedFiles.unshift({id,name:file.name,title,note});localStorage.setItem('memo-prototype-files-v1',JSON.stringify(state.addedFiles));toast('文件已保存，小忆会把它作为话题线索');rerenderPreserve()},true);
document.addEventListener('submit',e=>{if(e.target.id!=='friend-text-form')return;e.preventDefault();const text=String(new FormData(e.target).get('text')||'').trim();if(!text)return;state.friendMessages.push({to:state.followFriend,text});localStorage.setItem('memo-prototype-friend-chat-v1',JSON.stringify(state.friendMessages));rerenderPreserve()},true);
document.addEventListener('submit',e=>{if(e.target.id!=='agent-supplement-form')return;e.preventDefault();state.agentSupplement=String(new FormData(e.target).get('supplement')||'').trim();rerenderPreserve();toast(state.agentSupplement?'补充已记在边注':'今天可以先不补充')},true);
document.addEventListener('mouseenter',e=>{if(e.target.closest?.('#photo-stream'))state.timelinePaused=true},true);
document.addEventListener('mouseleave',e=>{if(e.target.closest?.('#photo-stream')&&!e.target.closest?.('.timeline-photo'))state.timelinePaused=false},true);
function communityBook(n){return `<div class="community-book-preview cb-${n.id}"><div class="cb-cover"><img src="${asset(n.image)}" alt=""><span><small>口述回忆册</small><strong>${esc(n.title)}</strong><em>${esc(n.name)} · 口述</em></span></div><div class="cb-page"><small>节选 · 第 1 页</small><h3>${esc(n.title)}</h3><p>${esc(n.text)}</p><b>01</b></div></div>`;}
communityPage=function(){return `<section class="screen community-final"><div class="topline"><span class="eyebrow">故事广场</span><button class="tiny-action" data-final="ai-open" data-context="community">小忆 ›</button></div><h1 class="subheading">听听他们的故事</h1>${assistantMini('community','听到一段熟悉的经历，也可以告诉我。')}<div class="section-head"><h2>专业访谈与写作</h2><span class="live-indicator">● 直播中</span></div><div class="pro-strip">${PROS.map(p=>`<button class="pro-card" data-extra="pro" data-id="${p.id}"><img class="pro-face" src="${asset(p.avatar)}" alt="${esc(p.name)}头像">${p.live?'<i class="live-pill">直播中</i>':''}<strong>${esc(p.name)}</strong><small>${esc(p.title)}</small><span>★ ${p.rating}</span></button>`).join('')}</div><div class="pro-note">访谈师与写作者可协助把确认过的内容做成专业版本。</div><div class="section-head"><h2>故事动态</h2></div>${COMMUNITY.map(n=>`<article class="moment-card"><div class="moment-person"><img src="${asset(n.avatar)}" alt="${esc(n.name)}头像"><span><strong>${esc(n.name)}</strong><small>${n.city} · ${n.tag}</small></span></div><p class="moment-copy">${esc(n.text)}</p><button class="moment-photos" data-extra="community" data-id="${n.id}"><img class="big" src="${asset(n.photos[0])}" alt="${esc(n.title)}"><img src="${asset(n.photos[1])}" alt=""><img src="${asset(n.photos[2])}" alt=""></button>${communityBook(n)}<div class="moment-actions"><button data-final="community-read" data-id="${n.id}">▶ 朗读</button><button data-final="community-share" data-id="${n.id}">分享</button><button data-extra="community" data-id="${n.id}">打开 ›</button></div></article>`).join('')}</section>`};
communityDetail=function(){const n=COMMUNITY.find(x=>x.id===state.selectedCommunity);if(!n)return communityPage();return `<section class="screen subscreen community-detail-final">${headerBack('广场')}<div class="moment-person"><img src="${asset(n.avatar)}" alt="${esc(n.name)}头像"><span><strong>${esc(n.name)}</strong><small>${n.age} 岁 · ${n.city}</small></span></div><h1 class="subheading">${esc(n.title)}</h1><p class="story-text">${esc(n.text)}</p><div class="detail-photo-grid">${n.photos.map(x=>`<img src="${asset(x)}" alt="${esc(n.title)}相关照片">`).join('')}</div><div class="section-head"><h2>这本回忆册</h2></div>${communityBook(n)}<div class="moment-actions"><button data-final="community-read" data-id="${n.id}">▶ 朗读故事</button><button data-final="community-share" data-id="${n.id}">分享</button></div><div class="section-head"><h2>听友评论</h2></div><div class="cm-list">${(n.comments||[]).map(c=>`<div class="cm-row"><strong>${esc(c[0])}</strong><p>${esc(c[1])}</p></div>`).join('')||'<p class="subtext">还没有评论。</p>'}</div></section>`};
proDetail=function(){const p=PROS.find(x=>x.id===state.selectedPro);if(!p)return communityPage();return `<section class="screen subscreen pro-final">${headerBack('专业服务')}<div class="pro-hero"><img src="${asset(p.avatar)}" alt="${esc(p.name)}头像"><div><h1>${esc(p.name)}</h1><p>${esc(p.title)} · ★ ${p.rating}</p>${p.live?'<i class="live-pill">直播中</i>':''}</div></div><div class="pro-workflow soft-card"><strong>合作方式</strong><p>先听你的原声与已确认的经历，再参考你授权的照片和家人线索安排访谈。写成专业版本后，由你逐段核对。</p></div><div class="section-head"><h2>选择服务</h2></div>${p.services.map((s,i)=>`<button class="option-row ${state.selectedService===i?'selected':''}" data-extra="service" data-id="${i}"><span><strong>${esc(s[0])}</strong><small>结合录音、照片与经过本人确认的事件</small></span><b>${esc(s[1])}</b></button>`).join('')}<button class="primary green full" data-extra="booking-pro" style="margin-top:14px">预览咨询方案</button></section>`};
const LISTENER_NOTES={
 yuzhen:[{name:'吴燕',avatar:'daughterinlaw',text:'我母亲也在纺织厂做过。读到每天早上开机那句，我一下想起她下班时的样子。'},{name:'许伯',avatar:'comrade',text:'车间的声音，离开很多年还是记得。谢谢你把这一段留了下来。'}],
 jianguo:[{name:'吴燕',avatar:'daughterinlaw',text:'我父亲说过北方站台上的风。你那句“把棉帽子压低”特别有画面。'}],
 suhua:[{name:'许伯',avatar:'comrade',text:'高第街那时真热闹。我也想起自己摆摊的第一天。'}],
 mingyuan:[{name:'吴燕',avatar:'daughterinlaw',text:'读到绑在钢梁上那句，才知道这座桥背后是怎样的人。'}]
};
const detailBeforeNotes=communityDetail;
communityDetail=function(){const n=COMMUNITY.find(x=>x.id===state.selectedCommunity);const notes=(LISTENER_NOTES[n?.id]||[]).map(c=>`<div class="listener-note"><img src="${asset(c.avatar)}" alt="${esc(c.name)}头像"><span><strong>${esc(c.name)}</strong><p>${esc(c.text)}</p></span></div>`).join('');return detailBeforeNotes().replace('<form id="comment-form"',notes+'<form id="comment-form"')};
GUIDES.splice(5,0,{id:'old-tool',kind:'旧物线索',source:'本人拍照 · 老物件',title:'父亲的那把刨子',q:'这件旧物你最先想起怎样用它？',img:'old-tool',method:'独立旧物先问使用和触感；不直接追问失去亲人的情绪。'});
GUIDES.push(
 {id:'liushi',kind:'少年经历',source:'默认话题',title:'柳市镇的早晨',q:'小时候一早出门，街上通常是什么样？',img:'old-workbench'},
 {id:'first-job',kind:'工作经历',source:'默认话题',title:'进电器厂的第一天',q:'第一天进厂，你先见到谁或哪件东西？',img:'workshop'},
 {id:'startup',kind:'工作经历',source:'默认话题',title:'和国平决定一起做',q:'你记得那次决定最初是怎样谈起来的吗？',img:'partner'},
 {id:'container',kind:'工作经历',source:'默认话题',title:'去码头看货装船',q:'你站在码头时，周围有什么画面现在还记得？',img:'expo'},
 {id:'handover',kind:'家人与工作',source:'默认话题',title:'把公司交给下一代',q:'思远第一次跟着国平工作，你记得那天怎样安排的？',img:'son'},
 {id:'mother-kitchen',kind:'家人故事',source:'默认话题',title:'母亲做的那顿饭',q:'说到家里吃饭，你先想起厨房里的什么？',img:'mother'},
 {id:'service-item',kind:'旧物线索',source:'本人拍照 · 退伍证',title:'退伍证',q:'看到这件旧物，你先想起拿到它的哪一天？',img:'train'},
 {id:'old-phone',kind:'旧物线索',source:'本人拍照 · 旧电话',title:'第一部办公室电话',q:'那部电话当时放在哪里？你还记得它响起来的声音吗？',img:'workshop'},
 {id:'factory-now',kind:'当下场景',source:'本人拍照 · 今天的厂房',title:'现在的厂房',q:'现在再走进这间厂房，哪一处最先让你想到过去？',img:'workshop'},
 {id:'blurry',kind:'模糊照片',source:'本人拍照 · 模糊合影',title:'认不清的旧合影',q:'就算照片不清楚，你还认得这是在什么地方吗？',img:'old-workbench'},
 {id:'lake-own',kind:'旅行照片',source:'本人拍照 · 西湖照片',title:'湖边的一段路',q:'你拍下这张照片前后，记得走了哪一段路？',img:'westlake'},
 {id:'wife-photo',kind:'协作线索',source:'协作端上传 · 美凤的照片',title:'美凤留着的合影',q:'看着这张照片，你记得那天从哪里来的？',img:'wife'},
 {id:'daughter-photo',kind:'协作线索',source:'协作端上传 · 思颖的童年照片',title:'思颖小时候',q:'你看到这张照片，先认出她在做什么？',img:'daughter'},
 {id:'son-document',kind:'文件线索',source:'协作端上传 · 思远的旧文件',title:'思远整理的文件',q:'看到这份文件，你记得这件事当时怎样开始的吗？',img:'son'},
 {id:'partner-dates',kind:'协作线索',source:'协作端上传 · 国平的时间记录',title:'国平记下的那一年',q:'这段时间里，你自己最先想起哪一件事？',img:'partner'},
 {id:'assistant-order',kind:'文件线索',source:'协作端上传 · 小吴的旧订单',title:'一份旧订单',q:'看到这份订单，你记得那一单是谁先接起来的吗？',img:'expo'},
 {id:'family-message',kind:'聊天线索',source:'协作端上传 · 家人聊天摘录',title:'家人提起的一句话',q:'家人提到这件事时，你自己先想到哪个画面？',img:'familytrip'},
 {id:'father-tool-photo',kind:'协作线索',source:'协作端上传 · 父亲留下的旧物',title:'父亲留下的一件东西',q:'这件东西以前放在哪里？',img:'old-tool'}
);
GUIDES.find(x=>x.id==='father').img='old-workbench';
state.guideIndex=GUIDES.findIndex(x=>x.id==='expo');
render();
