const $ = (s) => document.querySelector(s);
const viewport = $('#viewport');
const tabbar = $('#tabbar');
const asset = (name) => `assets/${name}.png`;
const people = [
  {id:'son',name:'陈思远',rel:'儿子',group:'家人',photo:'son',question:['爸，创业那些年，你是怎么过来的？','那段日子里，有没有一件事你现在还想起来？','我回国第一天上班，你当时心里在想什么？'],topics:['思远回国进公司第一天','父子之间一直没说出口的话'],records:[{id:'s1',title:'交接班那天的感想',length:'3分12秒',date:'9月10日'},{id:'s2',title:'对思远的期望',length:'2分05秒',date:'8月28日'}]},
  {id:'daughter',name:'陈思颖',rel:'女儿',group:'家人',photo:'daughter',question:['爸，你觉得这辈子最值得记下的一件事是什么？','我小时候，有什么样子你一直记得？'],topics:['思颖去上海那天','小时候一起过的周末'],records:[{id:'d1',title:'思颖去上海那天',length:'1分48秒',date:'7月15日'}]},
  {id:'wife',name:'林美凤',rel:'妻子',group:'家人',photo:'wife',question:[],topics:['第一次见面那天','创业时她说过的话'],records:[{id:'w1',title:'认识美凤那年',length:'2分44秒',date:'8月18日'},{id:'w2',title:'结婚前的那段时间',length:'3分20秒',date:'8月5日'},{id:'w3',title:'SARS 那年她说的话',length:'1分55秒',date:'7月22日'}]},
  {id:'father',name:'陈德厚',rel:'父亲',group:'家人',photo:'father',question:[],topics:['堂屋里的木匠工作台','父亲最常说的一句话'],records:[]},
  {id:'mother',name:'王秀兰',rel:'母亲',group:'家人',photo:'mother',question:['你记得奶奶做过什么菜吗？（思远想听）'],topics:['母亲的嫁妆故事','饭桌边的旧时光'],records:[{id:'m1',title:'母亲的嫁妆故事',length:'2分18秒',date:'7月3日'}]},
  {id:'partner',name:'赵国平',rel:'合伙人',group:'朋友',photo:'partner',question:['当年一起创业，你最先想起什么？'],topics:['第一个出口订单','2003 年那次争论'],records:[{id:'p1',title:'一起创业的决定',length:'4分10秒',date:'9月2日'},{id:'p2',title:'2003 年那次争论',length:'2分55秒',date:'8月14日'}]},
  {id:'comrade',name:'林建平',rel:'战友',group:'朋友',photo:'comrade',question:[],topics:['新兵第一周','退伍后的重逢'],records:[]},
  {id:'assistant',name:'小吴',rel:'助理',group:'其他',photo:'assistant',question:[],topics:['入职时的第一印象'],records:[]},
  {id:'daughterinlaw',name:'周婷',rel:'儿媳',group:'家人',photo:'daughterinlaw',question:[],topics:['第一次来家里'],records:[]},
  {id:'soninlaw',name:'李昊',rel:'女婿',group:'家人',photo:'soninlaw',question:[],topics:['思颖带他回家的那天'],records:[]},
  {id:'client',name:'阿兹曼',rel:'马来西亚老客户',group:'朋友',photo:'client',question:[],topics:['展会上相识','第一笔出口订单'],records:[]}
];
const memories = [
  {year:'1985',date:'1985 年 · 第一次远行',place:'绿皮火车上',title:'从车窗看见的田野',photo:'train',story:'第一次坐火车出远门是去看姨妈，从家出发要坐十二个小时。车厢里人很多。我靠着窗口，看外面的田野一片一片往后退。第一次看到连绵的丘陵，心里说不出的开阔。',person:'mother'},
  {year:'1994',date:'1994 年 · 认识美凤',place:'公司联谊会',title:'下雨天落下的一把伞',photo:'wife',story:'认识美凤是在公司的联谊会上。我本来不想去，是同事拉着去的。第一句话记不清了，只记得外面在下雨，她把伞落在了会场里。',person:'wife'},
  {year:'2003',date:'2003 年 · 最难的时候',place:'柳市镇',title:'她只问我“够不够”',photo:'narrator',story:'那年工厂停工，银行来催贷款。我把房子拿去抵押，先办了。后来美凤知道了，没骂我，只问一句“够不够”。我说够了。她说，那就行。',person:'wife'},
  {year:'2012',date:'2012 年 · 一家人出游',place:'杭州西湖',title:'西湖边慢慢走的一天',photo:'westlake',story:'那天没有安排很满的行程。大家沿着湖边慢慢走，思颖拿相机，思远走在前头。我记得风吹过来的时候，柳枝一直在晃。',person:'daughter'},
  {year:'2015',date:'2015 年 · 黄山',place:'黄山云海',title:'清晨四点等日出',photo:'huangshan',story:'爬黄山那年，我的腿还很有劲。清晨四点起来等日出，山上冷，风也很大。太阳从云海里升起来的时候，周围的人都不说话了。那种感觉照片拍不出来。',person:'son'}
];
const books = [
  {id:'life',title:'人生故事',kind:'口述自传',color:'#78533f',pages:[
    {type:'cover',title:'人生故事',subtitle:'陈建华 口述 · 2026'},
    {type:'chapter',label:'第一章 · 柳市镇的少年',title:'木匠父亲的工作台',text:'我父亲做木匠，工作台就放在堂屋里。刨花味我现在还记得，早上起来空气里就是那个味。\n\n他的手上有很多老茧，握锤子的地方最厚。他说一行吃透比什么都强。'},
    {type:'photo',label:'家人与旧时光',title:'她把伞落在会场里',photo:'wife',caption:'认识美凤 · 1994 年',text:'我们第一句话说了什么，我记不清了。只记得那天外面在下雨，她说话很直接。'},
    {type:'chapter',label:'第二章 · 当兵三年',title:'福建的部队生活',text:'新兵第一周就跑五公里。我从小没跑过那么多，第三天腿就肿了，但没跟班长说。\n\n后来慢慢跑习惯了，现在早上还是愿意出门走一走。'}]},
  {id:'work',title:'工作回忆',kind:'职场故事',color:'#244564',pages:[
    {type:'cover',title:'工作回忆',subtitle:'华辰二十六年 · 2026'},
    {type:'chapter',label:'第一章 · 跑业务那几年',title:'第一次出省跑单',text:'退伍第一年进了低压电器厂跑业务，第一次出省是去湖南，绿皮火车坐了一夜。\n\n行李箱里全是样品，提着很沉，但不觉得累。'},
    {type:'photo',label:'1999 年 · 华辰',title:'第一次走出去',photo:'partner',caption:'赵国平 · 合伙人',text:'那笔启动资金，我们两个来回商量了很多次。后来决定一起试试。'},
    {type:'chapter',label:'第二章 · 第一个出口订单',title:'我去码头看着货装船',text:'那个马来西亚客户是在展会上认识的。合同签完我没敢告诉国平，怕他以为我在吹牛。\n\n交货那天我自己去了码头，就站在那里，心里说不出是什么感觉。'}]},
  {id:'travel',title:'旅游故事',kind:'山河纪行',color:'#315a48',pages:[
    {type:'cover',title:'旅游故事',subtitle:'走过的地方 · 2026'},
    {type:'photo',label:'1985 年 · 第一次远行',title:'车窗外的田野',photo:'train',caption:'绿皮火车 · 远行',text:'我靠着窗口，第一次看到连绵的丘陵，心里说不出的开阔。'},
    {type:'photo',label:'2012 年 · 杭州',title:'西湖边的一天',photo:'westlake',caption:'杭州西湖 · 家庭旅行',text:'我们没有赶路，只是沿着湖边慢慢走。那样的日子，反而记得很牢。'},
    {type:'photo',label:'2015 年 · 黄山',title:'云海升起来的时候',photo:'huangshan',caption:'黄山 · 清晨四点',text:'太阳从云海里升起来的那一刻，周围的人都不说话了。只有站在那里才懂。'}]}
];
const icons = {
  home:'<path d="m3 10 9-7 9 7v10H3z"/><path d="M9 20v-7h6v7"/>',
  timeline:'<circle cx="5" cy="6" r="1"/><circle cx="5" cy="12" r="1"/><circle cx="5" cy="18" r="1"/><path d="M9 6h11M9 12h11M9 18h11"/>',
  people:'<circle cx="12" cy="7" r="3"/><path d="M5 20c0-4 3-6 7-6s7 2 7 6"/><path d="M3 7a2 2 0 0 1 3-2M21 7a2 2 0 0 0-3-2"/>',
  books:'<path d="M3 5c4-2 7-1 9 1 2-2 5-3 9-1v14c-4-2-7-1-9 1-2-2-5-3-9-1z"/><path d="M12 6v14"/>'
};
const saved = JSON.parse(localStorage.getItem('memo-prototype-v1') || '{}');
const state = {route:'home',personId:null,detailTab:'questions',group:'全部',memoryIndex:0,bookId:'life',pageIndex:0,read:saved.read||[],deleted:saved.deleted||[],added:saved.added||[],recordFor:null,recordTitle:'',recording:false,recordSeconds:0,stream:null,mediaRecorder:null,chunks:[],recordBlob:null,recordTimer:null,deleteId:null,flipLock:false};
const deepLink = new URLSearchParams(location.search);
if (['home','people','person','timeline','books','reader','audioall'].includes(deepLink.get('screen'))) state.route=deepLink.get('screen');
if (person(deepLink.get('person'))) state.personId=deepLink.get('person');
if (books.some(b=>b.id===deepLink.get('book'))) state.bookId=deepLink.get('book');
if (state.route==='person'&&!state.personId) state.route='people';
function persist(){localStorage.setItem('memo-prototype-v1',JSON.stringify({read:state.read,deleted:state.deleted,added:state.added}));}
function person(id){return people.find(p=>p.id===id);}
function activeRecords(p){return [...p.records,...state.added.filter(r=>r.personId===p.id)].filter(r=>!state.deleted.includes(r.id));}
function unreadCount(p){return p.question.filter((_,i)=>!state.read.includes(`${p.id}-${i}`)).length;}
function countAllUnread(){return people.reduce((n,p)=>n+unreadCount(p),0);}
function ownRecords(){return state.added.filter(r=>r.personId==='self'&&!state.deleted.includes(r.id));}
function countAllAudio(){return people.reduce((n,p)=>n+activeRecords(p).length,ownRecords().length);}
function esc(x){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function avatar(p,size=48){return `<img class="avatar" style="width:${size}px;height:${size}px" src="${asset(p.photo)}" alt="${esc(p.name)}头像">`;}
function headerBack(title){return `<div class="backline"><button class="back" data-action="back" aria-label="返回">‹</button><span>${esc(title)}</span></div>`;}
function tabMarkup(){const tabs=[['home','首页'],['timeline','时间轴'],['people','人物'],['books','我的书']];return tabs.map(([id,label])=>`<button class="tab ${state.route===id?'active':''}" data-route="${id}" aria-label="${label}" ${state.route===id?'aria-current="page"':''}><svg viewBox="0 0 24 24" aria-hidden="true">${icons[id]}</svg><span>${label}</span>${id==='people'&&countAllUnread()>0?'<i class="unread-dot" style="position:absolute;right:13px;top:2px;width:6px;height:6px"></i>':''}</button>`).join('');}
function home(){const featured=people.slice(0,4);return `<section class="screen"><div class="topline"><span class="eyebrow">把这一生，讲给想听的人</span><button class="tiny-action" data-route="books">我的书 ›</button></div><h1 class="hello">今天，谈谈和他们<br>的故事经历</h1><p class="subtext">从一个人、一张照片或一件小事开始。想说什么，就说什么。</p><div class="hero"><img src="${asset('narrator')}" alt="陈建华的照片"><div class="hero-text"><small>陈建华的回忆录</small><h2>那些年，我想慢慢讲给你听</h2><span>已留下的故事，随时可以翻看</span></div><button class="round-arrow" data-route="books" aria-label="打开我的书">›</button></div><div class="soft-card voice-cta"><div class="mic-orb"><svg width="25" height="25" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="9" y="2" width="6" height="12" rx="3"/><path d="M5 10a7 7 0 0 0 14 0M12 17v5M8 22h8"/></svg></div><div><strong>讲一段新的故事</strong><p>按下开始，用自己的话说</p></div><button data-action="record" aria-label="开始录音">›</button></div><div class="metrics"><button class="metric soft-card" data-route="people" style="text-align:left;border:1px solid var(--line)"><strong>${countAllUnread()}</strong><span>条未读提问 / ${people.reduce((n,p)=>n+p.question.length,0)} 条记录</span>${countAllUnread()?'<i class="unread-dot"></i>':''}</button><button class="metric soft-card" data-route="audioall" style="text-align:left;border:1px solid var(--line)"><strong>${countAllAudio()}</strong><span>条已录入语音 · 可管理删除</span></button></div><div class="section-head"><h2>和他们有关的故事</h2><button data-route="people">查看人物关系 ›</button></div><div class="people-strip">${featured.map(p=>`<button class="person-card" data-person="${p.id}">${avatar(p)}<span class="name">${p.name}</span><span class="rel">${p.rel}</span><div class="counts">${p.question.length} 条提问 · ${activeRecords(p).length} 条语音</div>${unreadCount(p)?'<i class="unread-dot"></i>':''}</button>`).join('')}</div><div class="section-head"><h2>照片里的时间</h2><button data-route="timeline">看时间轴 ›</button></div><button class="timeline-peek" data-route="timeline"><img src="${asset('huangshan')}" alt="黄山云海"><div><small>2015 年 · 黄山</small><strong>清晨四点等日出</strong><span>照片和原话，都留在那一天</span></div><b>›</b></button></section>`;}
function peoplePage(){const shown=people.filter(p=>state.group==='全部'||p.group===state.group);const map=people.slice(0,6);const pos=[[50,18],[19,32],[81,32],[20,75],[80,75],[50,83]];return `<section class="screen"><div class="topline"><span class="eyebrow">人物与关系</span><span style="color:var(--muted);font-size:11px">${people.length} 位有故事的人</span></div><h1 class="subheading">谁在我的故事里</h1><p class="subtext">点开一个人，看 TA 想听什么、你已经讲过什么。</p><div class="relation-map"><svg viewBox="0 0 340 290" preserveAspectRatio="none" aria-hidden="true"><line x1="170" y1="135" x2="170" y2="48"/><line x1="170" y1="135" x2="65" y2="93"/><line x1="170" y1="135" x2="275" y2="93"/><line x1="170" y1="135" x2="65" y2="218"/><line x1="170" y1="135" x2="275" y2="218"/><line x1="170" y1="135" x2="170" y2="240"/></svg><div class="map-node center" style="left:50%;top:47%"><img src="${asset('narrator')}" alt="陈建华头像"><span>我 · 建华</span></div>${map.map((p,i)=>`<button class="map-node" style="left:${pos[i][0]}%;top:${pos[i][1]}%" data-person="${p.id}"><img src="${asset(p.photo)}" alt="${p.name}头像"><span>${p.name}</span>${unreadCount(p)?'<i class="unread-dot"></i>':''}</button>`).join('')}</div><div class="filter-row">${['全部','家人','朋友','其他'].map(g=>`<button class="${state.group===g?'selected':''}" data-group="${g}">${g}</button>`).join('')}</div><div class="person-list">${shown.map(p=>`<button class="person-row" data-person="${p.id}">${avatar(p,47)}<span><strong>${p.name}</strong><small>${p.rel} · ${p.question.length} 条提问 · ${activeRecords(p).length} 条语音</small></span><span class="row-right">${unreadCount(p)?`<i class="unread-dot"></i><span>${unreadCount(p)}</span>`:''} ›</span></button>`).join('')}</div></section>`;}
function personPage(){const p=person(state.personId);if(!p)return home();const recs=activeRecords(p);let body='';if(state.detailTab==='questions'){body=p.question.length?p.question.map((q,i)=>{const id=`${p.id}-${i}`;const unread=!state.read.includes(id);return `<div class="note-card soft-card ${unread?'unread':''}"><small>来自 ${p.name} 的提问</small><p>“${esc(q)}”</p>${unread?`<i class="unread-dot"></i><button data-read="${id}">标记已读</button>`:'<small>已读</small>'}</div>`;}).join(''):`<div class="empty">${p.name}还没有留下提问。<br>你可以从你们共同经历的一件小事开始讲。</div>`;}else if(state.detailTab==='audio'){body=recs.length?recs.map(r=>`<div class="audio-row"><button class="play" data-play="${r.id}" aria-label="播放${esc(r.title)}">▶</button><span><strong>${esc(r.title)}</strong><small>${esc(r.date)} · ${esc(r.length)}${r.user?' · 我的录音':''}</small></span><button class="delete" data-delete="${r.id}" aria-label="删除${esc(r.title)}">删除</button></div>`).join(''):`<div class="empty">还没有与${p.name}有关的语音。<br>录一段，你们的故事就从这里开始。</div>`;}else{body=p.topics.map(t=>`<div class="note-card soft-card"><small>可聊的话题 · 不作为事实</small><p>${esc(t)}</p><button data-topic="${esc(t)}">就从这件事讲起 ›</button></div>`).join('');}return `<section class="screen subscreen">${headerBack(state.personFrom==='people'?'人物关系':'返回')}<div class="profile-hero">${avatar(p,78)}<div><h1>${p.name}</h1><p>${p.rel} · 和他有关的故事</p></div></div><div class="profile-stats"><div><strong>${p.question.length}</strong><span>提问记录${unreadCount(p)?' · 未读 '+unreadCount(p):''}</span></div><div><strong>${recs.length}</strong><span>已录入语音</span></div><div><strong>${p.topics.length}</strong><span>可聊的故事</span></div></div><div class="segment-tabs"><button data-detail="questions" class="${state.detailTab==='questions'?'selected':''}">他想听的 ${unreadCount(p)?'●':''}</button><button data-detail="audio" class="${state.detailTab==='audio'?'selected':''}">我的语音</button><button data-detail="topics" class="${state.detailTab==='topics'?'selected':''}">故事线索</button></div>${body}<div style="height:12px"></div><button class="primary green full" data-action="record-person">谈谈和${p.name}的故事</button><p class="subtext" style="text-align:center;margin-top:10px">想不起来也可以先跳过，系统不会催你。</p></section>`;}
function audioAllPage(){const rows=[...people.flatMap(p=>activeRecords(p).map(r=>({...r,who:p.name}))),...ownRecords().map(r=>({...r,who:'我的故事'}))];return `<section class="screen subscreen">${headerBack('首页')}<span class="eyebrow">我的语音记录</span><h1 class="subheading">已经说过的故事</h1><p class="subtext">${rows.length} 条语音，可以回听，也可以删除。</p><div style="height:20px"></div>${rows.map(r=>`<div class="audio-row"><button class="play" data-play="${r.id}" aria-label="播放${esc(r.title)}">▶</button><span><strong>${esc(r.title)}</strong><small>${esc(r.who)} · ${esc(r.date)} · ${esc(r.length)}</small></span><button class="delete" data-delete="${r.id}" aria-label="删除${esc(r.title)}">删除</button></div>`).join('')||'<div class="empty">还没有留下语音。想说的时候再开始。</div>'}<div style="height:14px"></div><button class="primary green full" data-action="record">再录一段</button></section>`;}
function timelinePage(){const m=memories[state.memoryIndex];return `<section class="screen"><div class="topline"><span class="eyebrow">照片时间轴</span><span style="color:var(--muted);font-size:11px">${state.memoryIndex+1} / ${memories.length}</span></div><h1 class="subheading">一张照片，一段往事</h1><p class="subtext">左右滑动照片，沿时间往前或往后走。</p><div class="photo-stream" id="photo-stream">${memories.map((x,i)=>`<button class="polaroid ${i===state.memoryIndex?'active':''}" data-memory="${i}"><img src="${asset(x.photo)}" alt="${esc(x.title)}"><small>${x.date}</small><strong>${x.title}</strong></button>`).join('')}</div><div class="year-rail">${memories.map((x,i)=>`<button data-memory="${i}" class="${i===state.memoryIndex?'active':''}" aria-label="跳到${x.year}年"></button>`).join('')}</div><div class="timeline-detail soft-card"><small>${m.place} · ${m.date}</small><h2>${m.title}</h2><p>${m.story}</p><button class="text-link" data-person="${m.person}">看看故事里的人 ›</button></div><div class="section-head"><h2>让照片开口</h2></div><button class="primary green full" data-action="record-memory">说说我记得的那一天</button></section>`;}
function booksPage(){return `<section class="screen"><div class="topline"><span class="eyebrow">我的书架</span><span style="font-size:11px;color:var(--muted)">原话慢慢攒成书</span></div><h1 class="subheading">不同的故事，不同的书</h1><p class="subtext">选一本翻开。旅行书以照片为主，人生与工作回忆保留讲述原话。</p><div class="books-grid">${books.map(b=>`<button class="book-tile" data-book="${b.id}"><div class="book-cover" style="background:${b.color}"><span class="cover-mark">回 忆 录</span><h3>${b.title}</h3><span class="cover-foot">陈建华 · 口述</span></div><strong>${b.title}</strong><small>${b.kind}</small></button>`).join('')}</div><div class="book-note soft-card">书的篇幅、照片和装帧可以不同；故事的口气仍是讲述者自己的。翻页只是阅读方式，不改变原话。</div><div class="section-head"><h2>最近留下的段落</h2></div><button class="timeline-peek" data-book="life"><img src="${asset('father')}" alt="父亲的旧照片"><div><small>第一章 · 柳市镇的少年</small><strong>木匠父亲的工作台</strong><span>刨花味，我现在还记得</span></div><b>›</b></button></section>`;}
function pageContent(b,page,i){if(page.type==='cover')return `<div class="book-page cover-page" style="background:${b.color}"><small class="chapter-label">银发回忆录 · ${b.kind}</small><h2>${page.title}</h2><div class="cover-line"></div><p>${page.subtitle}</p><span class="page-number">${i+1}</span></div>`;return `<div class="book-page"><span class="chapter-label">${page.label}</span><h2>${page.title}</h2>${page.photo?`<img class="page-photo" src="${asset(page.photo)}" alt="${page.title}"><span class="caption">${page.caption}</span>`:''}<p>${page.text}</p><span class="page-number">${i+1}</span></div>`;}
function readerPage(){const b=books.find(x=>x.id===state.bookId);const p=b.pages[state.pageIndex];return `<section class="screen subscreen">${headerBack('我的书架')}<div class="book-reader-head"><small>${b.kind}</small><h1>${b.title}</h1></div><div class="book-stage" id="book-stage"><div class="paper-stack" id="paper-stack">${pageContent(b,p,state.pageIndex)}</div></div><div class="reader-controls"><button data-page="prev" ${state.pageIndex===0?'disabled':''} aria-label="上一页">‹</button><span>${state.pageIndex+1} / ${b.pages.length} · 左右滑动翻页</span><button data-page="next" ${state.pageIndex===b.pages.length-1?'disabled':''} aria-label="下一页">›</button></div><p class="subtext" style="text-align:center;margin-top:17px">这只是阅读样式预览，正文保留讲述原话。</p></section>`;}
function recordPage(){const p=state.recordFor?person(state.recordFor):null;return `<section class="screen subscreen">${headerBack(p?`和${p.name}的故事`:'讲一段故事')}<span class="eyebrow">录音</span><h1 class="subheading">${p?`说说和${p.name}的事`:'今天想说点什么？'}</h1>${state.recordTitle?`<div class="question-prompt"><small>你选的话题 · 可随时换</small><p>${esc(state.recordTitle)}</p><span>这只是起话头，不会写成事实。</span></div>`:''}<div class="record-panel"><div class="record-orb ${state.recording?'':'paused'}">${state.recording?'◉':'<img class="orb-mic" src="assets/ic-mic.png" alt="">'}</div><div class="wave ${state.recording?'':'still'}">${Array.from({length:21},(_,i)=>`<i style="--h:${14+(i*17)%54}px;--d:${(i%7)*-0.13}s"></i>`).join('')}</div><div class="record-time">${formatSecs(state.recordSeconds)}</div><p class="record-help">${state.recording?'正在录下这段讲述':'点按开始后进入录音演示'}</p><div class="record-actions">${state.recording?`<button class="ghost" data-action="pause-record">暂停</button><button class="primary" data-action="finish-record">完成录制</button>`:`<button class="primary full" data-action="start-record">开始录下我的原声</button>`}</div><button class="tiny-action" data-action="skip-record" style="margin-top:16px">今天先不讲</button></div></section>`;}
function previewPage(){const p=state.recordFor?person(state.recordFor):null;return `<section class="screen subscreen">${headerBack('回听这一段')}<span class="eyebrow">先听自己说的话</span><h1 class="subheading">这段，是不是你想留下的？</h1><p class="subtext">确认后才会记到语音里。现在不保存也可以。</p><div class="record-preview soft-card"><strong>${p?`和${p.name}的故事`:'今天讲的一段'}</strong><p>这段录音保持原声。原型不会替你改写、补上没说过的人名或年份。</p><button class="ghost" data-action="play-preview">▶ 回听 ${formatSecs(state.recordSeconds)}</button></div><div class="record-actions"><button class="ghost" data-action="discard-record">不保存</button><button class="primary green" data-action="save-record">保存</button></div></section>`;}
function dialog(){const r=[...people.flatMap(p=>activeRecords(p)),...ownRecords()].find(x=>x.id===state.deleteId);return `<div class="delete-modal"><div class="dialog"><h2>删除这条语音？</h2><p>“${r?esc(r.title):'这条录音'}”会从故事记录里移除。确认后，首页的语音条数也会更新。</p><div class="record-actions"><button class="ghost" data-action="cancel-delete">再想想</button><button class="ghost danger" data-action="confirm-delete">删除语音</button></div></div></div>`;}
function render(){let html={home,people:peoplePage,person:personPage,audioall:audioAllPage,timeline:timelinePage,books:booksPage,reader:readerPage,record:recordPage,preview:previewPage}[state.route]();viewport.innerHTML=html+(state.deleteId?dialog():'');const isMain=['home','people','timeline','books'].includes(state.route);tabbar.innerHTML=isMain?tabMarkup():'';tabbar.classList.toggle('hidden',!isMain);if(state.route==='timeline'){const stream=$('#photo-stream');stream.children[state.memoryIndex]?.scrollIntoView({block:'nearest',inline:'center'});bindStream(stream);}if(state.route==='reader')bindBookSwipe();}
function route(id){state.route=id;state.deleteId=null;render();viewport.querySelector('.screen')?.scrollTo(0,0);}
function back(){if(state.route==='person')route(state.personFrom&&state.personFrom!=='person'?state.personFrom:'people');else if(state.route==='audioall')route('home');else if(state.route==='reader')route('books');else if(state.route==='record'){cleanupRecording();route(state.recordFor?'person':'home');}else if(state.route==='preview')route('record');else route('home');}
function toast(message){const box=$('#toast');box.textContent=message;box.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>box.classList.remove('show'),2600);}
function formatSecs(n){return `${Math.floor(n/60).toString().padStart(2,'0')}:${(n%60).toString().padStart(2,'0')}`;}
function selectMemory(i){state.memoryIndex=Math.max(0,Math.min(memories.length-1,i));render();}
function turnPage(direction){if(state.flipLock)return;const b=books.find(x=>x.id===state.bookId);const next=state.pageIndex+(direction==='next'?1:-1);if(next<0||next>=b.pages.length)return;state.flipLock=true;const page=$('#paper-stack .book-page');page.classList.add(direction==='next'?'flipping-next':'flipping-prev');setTimeout(()=>{state.pageIndex=next;state.flipLock=false;render();},620);}
function bindBookSwipe(){const stage=$('#book-stage');let x=0,y=0;stage.addEventListener('touchstart',e=>{x=e.touches[0].clientX;y=e.touches[0].clientY},{passive:true});stage.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-x;const dy=e.changedTouches[0].clientY-y;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.3)turnPage(dx<0?'next':'prev')},{passive:true});}
function bindStream(stream){let timer;stream.addEventListener('scroll',()=>{clearTimeout(timer);timer=setTimeout(()=>{const cards=[...stream.children];const center=stream.scrollLeft+stream.clientWidth/2;const idx=cards.reduce((best,c,i)=>Math.abs(c.offsetLeft+c.offsetWidth/2-center)<Math.abs(cards[best].offsetLeft+cards[best].offsetWidth/2-center)?i:best,0);if(idx!==state.memoryIndex){state.memoryIndex=idx;const panel=$('.timeline-detail');const m=memories[idx];panel.innerHTML=`<small>${m.place} · ${m.date}</small><h2>${m.title}</h2><p>${m.story}</p><button class="text-link" data-person="${m.person}">看看故事里的人 ›</button>`;$('.topline span:last-child').textContent=`${idx+1} / ${memories.length}`;document.querySelectorAll('.year-rail button,.polaroid').forEach((c,i)=>c.classList.toggle('active',i%memories.length===idx));}},85)},{passive:true});}
function openAudioDb(){return new Promise((resolve,reject)=>{if(!('indexedDB'in window))return reject(new Error('no db'));const req=indexedDB.open('memo-prototype-audio',2);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains('clips'))req.result.createObjectStore('clips');if(!req.result.objectStoreNames.contains('photos'))req.result.createObjectStore('photos')};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
async function dbPut(id,blob){try{const db=await openAudioDb();const tx=db.transaction('clips','readwrite');tx.objectStore('clips').put(blob,id);await new Promise((res,rej)=>{tx.oncomplete=res;tx.onerror=rej});db.close();return true;}catch{return false;}}
async function dbGet(id){try{const db=await openAudioDb();const tx=db.transaction('clips','readonly');const request=tx.objectStore('clips').get(id);const blob=await new Promise((res,rej)=>{request.onsuccess=()=>res(request.result);request.onerror=rej});db.close();return blob;}catch{return null;}}
async function dbDelete(id){try{const db=await openAudioDb();const tx=db.transaction('clips','readwrite');tx.objectStore('clips').delete(id);db.close();}catch{}}
function cleanupRecording(){clearInterval(state.recordTimer);state.recordTimer=null;if(state.mediaRecorder?.state==='recording')state.mediaRecorder.stop();state.stream?.getTracks().forEach(t=>t.stop());state.stream=null;state.mediaRecorder=null;state.recording=false;}
async function startRecording(){clearInterval(state.recordTimer);state.chunks=[];state.recordSeconds=0;state.recordBlob=null;state.recording=true;state.recordTimer=setInterval(()=>{state.recordSeconds++;$('.record-time')?.replaceChildren(document.createTextNode(formatSecs(state.recordSeconds)));window.updateLiveTranscript?.(state.recordSeconds)},1000);render();}
async function finishRecording(){state.recording=false;clearInterval(state.recordTimer);state.recordTimer=null;state.recordBlob=new Blob([],{type:'audio/webm'});route('preview');}
async function playAudio(id){const r=state.added.find(x=>x.id===id);if(!r){toast('示例语音仅展示记录，原始音频未附在原型中');return;}const blob=await dbGet(id);if(!blob||!blob.size){toast('演示记录没有附带真实原音频');return;}const url=URL.createObjectURL(blob);const audio=new Audio(url);audio.onended=()=>URL.revokeObjectURL(url);audio.onerror=()=>{URL.revokeObjectURL(url);toast('音频播放失败')};audio.play().catch(()=>toast('请点按播放后重试'));}
function openRecord(personId=null,title=''){state.recordFor=personId;state.recordTitle=title;state.recordSeconds=0;state.recordBlob=null;route('record');}
function handleClick(e){const el=e.target.closest('button[data-route],button[data-person],button[data-action],button[data-group],button[data-detail],button[data-read],button[data-delete],button[data-play],button[data-topic],button[data-memory],button[data-book],button[data-page]');if(!el)return;if(el.dataset.route)return route(el.dataset.route);if(el.dataset.person){state.personId=el.dataset.person;state.detailTab='questions';state.personFrom=state.route;return route('person');}if(el.dataset.group){state.group=el.dataset.group;return render();}if(el.dataset.detail){state.detailTab=el.dataset.detail;return render();}if(el.dataset.read){if(!state.read.includes(el.dataset.read))state.read.push(el.dataset.read);persist();return render();}if(el.dataset.delete){state.deleteId=el.dataset.delete;return render();}if(el.dataset.play)return playAudio(el.dataset.play);if(el.dataset.topic)return openRecord(state.personId,el.dataset.topic);if(el.dataset.memory)return selectMemory(Number(el.dataset.memory));if(el.dataset.book){state.bookId=el.dataset.book;state.pageIndex=0;return route('reader');}if(el.dataset.page)return turnPage(el.dataset.page);switch(el.dataset.action){case 'back':return back();case 'record':return openRecord();case 'record-memory':return openRecord(null,memories[state.memoryIndex].title);case 'record-person':return openRecord(state.personId);case 'start-record':return startRecording();case 'pause-record':if(state.recording){state.recording=false;clearInterval(state.recordTimer);state.recordTimer=null;render();const b=$('.record-actions');if(b)b.innerHTML='<button class="ghost" data-action="resume-record">继续</button><button class="primary" data-action="finish-record">完成录制</button>';}return;case 'resume-record':state.recording=true;clearInterval(state.recordTimer);state.recordTimer=setInterval(()=>{state.recordSeconds++;$('.record-time')?.replaceChildren(document.createTextNode(formatSecs(state.recordSeconds)));window.updateLiveTranscript?.(state.recordSeconds)},1000);return render();case 'finish-record':return finishRecording();case 'skip-record':cleanupRecording();return route(state.recordFor?'person':'home');case 'play-preview':toast('原型演示：已响应回听操作');return;case 'discard-record':state.recordBlob=null;return route(state.recordFor?'person':'home');case 'save-record':return saveRecording();case 'cancel-delete':state.deleteId=null;return render();case 'confirm-delete':state.deleted.push(state.deleteId);dbDelete(state.deleteId);state.deleteId=null;persist();toast('已删除语音');return render();}}
async function saveRecording(){if(!state.recordBlob)return;const id=`new-${Date.now()}`;const p=state.recordFor||'self';const today=new Date();const title=state.recordTitle||(p==='self'?'今天讲的一段故事':`和${person(p)?.name}的一段故事`);const rec={id,personId:p,title,length:formatSecs(state.recordSeconds),date:`${today.getMonth()+1}月${today.getDate()}日`,user:true,mock:true};state.added.push(rec);persist();state.recordBlob=null;toast('这段讲述已加入记录');if(p==='self')route('audioall');else{state.personId=p;state.detailTab='audio';route('person');}}
document.addEventListener('click',handleClick);
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(state.deleteId){state.deleteId=null;render();}else back();}if(state.route==='reader'&&e.key==='ArrowRight')turnPage('next');if(state.route==='reader'&&e.key==='ArrowLeft')turnPage('prev');if(state.route==='timeline'&&e.key==='ArrowRight')selectMemory(state.memoryIndex+1);if(state.route==='timeline'&&e.key==='ArrowLeft')selectMemory(state.memoryIndex-1);});
const now=new Date();$('#clock').textContent=`${now.getHours().toString().padStart(2,'0')}:${now.getMinutes().toString().padStart(2,'0')}`;
render();
